// One time generator for the WordSetu seed dictionary.
//
// Authors an original CC0 seed dataset of common Bangla words. Every field here
// is original content written for WordSetu and is not copied from any
// copyrighted dictionary. Run with: node scripts/gen-seed.mjs
//
// The output is written to resources/dictionary/entries.json. This script is a
// build time authoring aid; the generated JSON is the checked in source of
// truth for the dictionary data.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'resources', 'dictionary', 'entries.json');

// Each tuple: [id, headword(bn), roman, pos, ipa, defBn, defEn, synonyms[], example?]
// example is [bn, en] or null. Content is original and public domain (CC0).
const rows = [
  ['ami', 'আমি', 'ami', 'pronoun', 'ami', 'কথা বলা ব্যক্তি নিজেকে যে শব্দে বোঝায়।', 'I', [], ['আমি বাড়ি যাচ্ছি।', 'I am going home.']],
  ['tumi', 'তুমি', 'tumi', 'pronoun', 'tumi', 'যাকে সম্বোধন করা হয় তাকে ঘনিষ্ঠভাবে বোঝানোর শব্দ।', 'you', [], ['তুমি কেমন আছ?', 'How are you?']],
  ['apni', 'আপনি', 'apni', 'pronoun', 'apni', 'সম্মানসূচকভাবে দ্বিতীয় ব্যক্তিকে বোঝানোর শব্দ।', 'you (respectful)', [], ['আপনি বসুন।', 'Please sit down.']],
  ['se', 'সে', 'she', 'pronoun', 'ʃe', 'তৃতীয় কোনো ব্যক্তিকে বোঝানোর শব্দ।', 'he; she', [], ['সে এখন এখানে নেই।', 'He is not here now.']],
  ['boi', 'বই', 'boi', 'noun', 'boi', 'ছাপানো বা লেখা পৃষ্ঠার বাঁধাই করা সংকলন।', 'book', ['পুস্তক', 'গ্রন্থ'], ['আমি একটি বই পড়ছি।', 'I am reading a book.']],
  ['jol', 'জল', 'jol', 'noun', 'dʒɔl', 'বর্ণহীন স্বচ্ছ তরল যা পান করা হয়।', 'water', ['পানি', 'বারি'], ['গ্লাসে জল আছে।', 'There is water in the glass.']],
  ['pani', 'পানি', 'pani', 'noun', 'pani', 'পানের যোগ্য স্বচ্ছ তরল।', 'water', ['জল', 'বারি'], ['আমাকে একটু পানি দাও।', 'Give me some water.']],
  ['agun', 'আগুন', 'agun', 'noun', 'agun', 'জ্বলন্ত তাপ ও আলো উৎপন্নকারী দহন।', 'fire', ['অগ্নি', 'হুতাশন'], ['আগুন খুব গরম।', 'Fire is very hot.']],
  ['batas', 'বাতাস', 'batas', 'noun', 'batas', 'চলমান বায়ু।', 'wind; air', ['হাওয়া', 'বায়ু'], ['ঠান্ডা বাতাস বইছে।', 'A cold wind is blowing.']],
  ['akash', 'আকাশ', 'akash', 'noun', 'akaʃ', 'পৃথিবীর উপরে বিস্তৃত নীল শূন্যস্থান।', 'sky', ['গগন', 'নভ'], ['আকাশ আজ পরিষ্কার।', 'The sky is clear today.']],
  ['mati', 'মাটি', 'mati', 'noun', 'mati', 'পৃথিবীর উপরিভাগের নরম স্তর যেখানে গাছ জন্মায়।', 'soil; earth', ['ভূমি', 'জমি'], ['মাটিতে বীজ বোনা হয়।', 'Seeds are sown in the soil.']],
  ['surjo', 'সূর্য', 'surjo', 'noun', 'ʃurdʒo', 'যে নক্ষত্র থেকে পৃথিবী আলো ও তাপ পায়।', 'sun', ['রবি', 'ভানু'], ['সকালে সূর্য ওঠে।', 'The sun rises in the morning.']],
  ['chand', 'চাঁদ', 'chand', 'noun', 'tʃãd', 'রাতের আকাশে দৃশ্যমান পৃথিবীর উপগ্রহ।', 'moon', ['শশী', 'ইন্দু'], ['আজ রাতে চাঁদ উঠেছে।', 'The moon has risen tonight.']],
  ['tara', 'তারা', 'tara', 'noun', 'tara', 'রাতের আকাশে জ্বলজ্বল করা দূরবর্তী নক্ষত্র।', 'star', ['নক্ষত্র', 'উডু'], ['আকাশে অনেক তারা।', 'There are many stars in the sky.']],
  ['gachh', 'গাছ', 'gachh', 'noun', 'gatʃʰ', 'শিকড়, কাণ্ড ও পাতা যুক্ত উদ্ভিদ।', 'tree; plant', ['বৃক্ষ', 'তরু'], ['বাড়ির সামনে একটি গাছ আছে।', 'There is a tree in front of the house.']],
  ['phul', 'ফুল', 'phul', 'noun', 'pʰul', 'গাছের রঙিন সুগন্ধি প্রজনন অংশ।', 'flower', ['পুষ্প', 'কুসুম'], ['বাগানে ফুল ফুটেছে।', 'Flowers have bloomed in the garden.']],
  ['pakhi', 'পাখি', 'pakhi', 'noun', 'pakʰi', 'পালকযুক্ত উড়তে সক্ষম প্রাণী।', 'bird', ['বিহঙ্গ', 'খেচর'], ['পাখি গান গায়।', 'The bird sings.']],
  ['machh', 'মাছ', 'machh', 'noun', 'matʃʰ', 'জলে বাস করা কানকো ও পাখনাযুক্ত প্রাণী।', 'fish', ['মীন', 'মৎস্য'], ['নদীতে মাছ আছে।', 'There are fish in the river.']],
  ['ghar', 'ঘর', 'ghar', 'noun', 'gʰɔr', 'বসবাসের জন্য নির্মিত কক্ষ বা বাসস্থান।', 'room; house', ['কক্ষ', 'গৃহ'], ['ঘরটি বড় ও পরিষ্কার।', 'The room is big and clean.']],
  ['bari', 'বাড়ি', 'bari', 'noun', 'baɽi', 'পরিবারের বসবাসের স্থান।', 'home; house', ['গৃহ', 'নিবাস'], ['সে বাড়ি ফিরেছে।', 'He has returned home.']],
  ['school', 'স্কুল', 'skul', 'noun', 'skul', 'যেখানে ছাত্রছাত্রীরা শিক্ষা লাভ করে।', 'school', ['বিদ্যালয়', 'পাঠশালা'], ['শিশুরা স্কুলে যায়।', 'The children go to school.']],
  ['boi_ghor', 'গ্রন্থাগার', 'granthagar', 'noun', 'grɔntʰagar', 'যেখানে বই সংগ্রহ ও পাঠ করা হয়।', 'library', ['পাঠাগার'], ['গ্রন্থাগারে অনেক বই আছে।', 'There are many books in the library.']],
  ['shohor', 'শহর', 'shohor', 'noun', 'ʃɔhor', 'ঘনবসতিপূর্ণ বড় জনপদ।', 'city; town', ['নগর', 'পুর'], ['শহরে অনেক মানুষ থাকে।', 'Many people live in the city.']],
  ['gram', 'গ্রাম', 'gram', 'noun', 'gram', 'ছোট গ্রামীণ জনবসতি।', 'village', ['পল্লি', 'পাড়াগাঁ'], ['আমার গ্রাম খুব সুন্দর।', 'My village is very beautiful.']],
  ['rasta', 'রাস্তা', 'rasta', 'noun', 'rasta', 'চলাচলের জন্য নির্মিত পথ।', 'road; street', ['পথ', 'সড়ক'], ['রাস্তা দিয়ে গাড়ি চলে।', 'Cars run on the road.']],
  ['nodi', 'নদী', 'nodi', 'noun', 'nodi', 'প্রবাহিত মিষ্টি জলের বড় ধারা।', 'river', ['তটিনী', 'স্রোতস্বিনী'], ['নদীতে নৌকা চলছে।', 'Boats are sailing on the river.']],
  ['shagor', 'সাগর', 'shagor', 'noun', 'ʃagor', 'বিশাল লবণাক্ত জলরাশি।', 'sea; ocean', ['সমুদ্র', 'জলধি'], ['সাগরের ঢেউ বড়।', 'The waves of the sea are big.']],
  ['pahar', 'পাহাড়', 'pahar', 'noun', 'pahaɽ', 'ভূমি থেকে উঁচু বিশাল শিলাস্তূপ।', 'mountain; hill', ['পর্বত', 'গিরি'], ['পাহাড়ে বরফ জমে।', 'Snow gathers on the mountain.']],
  ['bon', 'বন', 'bon', 'noun', 'bɔn', 'ঘন গাছপালায় ঢাকা এলাকা।', 'forest', ['অরণ্য', 'জঙ্গল'], ['বনে বাঘ থাকে।', 'Tigers live in the forest.']],
  ['manush', 'মানুষ', 'manush', 'noun', 'manuʃ', 'বুদ্ধিসম্পন্ন সামাজিক প্রাণী।', 'human; person', ['লোক', 'জন'], ['মানুষ সমাজে বাস করে।', 'Humans live in society.']],
  ['chhele', 'ছেলে', 'chhele', 'noun', 'tʃʰele', 'পুরুষ সন্তান বা বালক।', 'boy; son', ['বালক', 'পুত্র'], ['ছেলেটি মাঠে খেলছে।', 'The boy is playing in the field.']],
  ['meye', 'মেয়ে', 'meye', 'noun', 'meje', 'নারী সন্তান বা বালিকা।', 'girl; daughter', ['বালিকা', 'কন্যা'], ['মেয়েটি গান শেখে।', 'The girl learns to sing.']],
  ['baba', 'বাবা', 'baba', 'noun', 'baba', 'পিতা, জন্মদাতা পুরুষ অভিভাবক।', 'father', ['পিতা', 'জনক'], ['বাবা অফিসে গেছেন।', 'Father has gone to the office.']],
  ['ma', 'মা', 'ma', 'noun', 'ma', 'জননী, জন্মদাত্রী নারী অভিভাবক।', 'mother', ['জননী', 'মাতা'], ['মা রান্না করছেন।', 'Mother is cooking.']],
  ['bhai', 'ভাই', 'bhai', 'noun', 'bʱai', 'একই পিতামাতার পুরুষ সন্তান।', 'brother', ['ভ্রাতা', 'সহোদর'], ['আমার একটি ছোট ভাই আছে।', 'I have a younger brother.']],
  ['bon_r', 'বোন', 'bon', 'noun', 'bon', 'একই পিতামাতার নারী সন্তান।', 'sister', ['ভগিনী', 'সহোদরা'], ['বোন আমাকে সাহায্য করে।', 'My sister helps me.']],
  ['bondhu', 'বন্ধু', 'bondhu', 'noun', 'bondʱu', 'যাকে বিশ্বাস ও ভালোবাসা যায় এমন সঙ্গী।', 'friend', ['মিত্র', 'সখা'], ['সে আমার ভালো বন্ধু।', 'He is my good friend.']],
  ['shikkhok', 'শিক্ষক', 'shikkhok', 'noun', 'ʃikkʰok', 'যিনি শিক্ষা দেন।', 'teacher', ['গুরু', 'অধ্যাপক'], ['শিক্ষক পড়ান।', 'The teacher teaches.']],
  ['chhatro', 'ছাত্র', 'chhatro', 'noun', 'tʃʰatro', 'যে শিক্ষা গ্রহণ করে।', 'student', ['শিক্ষার্থী', 'শিষ্য'], ['ছাত্র মন দিয়ে পড়ে।', 'The student studies attentively.']],
  ['daktar', 'ডাক্তার', 'daktar', 'noun', 'daktar', 'যিনি রোগ চিকিৎসা করেন।', 'doctor', ['চিকিৎসক', 'বৈদ্য'], ['ডাক্তার রোগী দেখছেন।', 'The doctor is examining the patient.']],
  ['krishok', 'কৃষক', 'krishok', 'noun', 'kriʃok', 'যিনি জমি চাষ করেন।', 'farmer', ['চাষি', 'কৃষিজীবী'], ['কৃষক মাঠে কাজ করে।', 'The farmer works in the field.']],
  ['kaj', 'কাজ', 'kaj', 'noun', 'kadʒ', 'যা সম্পন্ন করতে হয় এমন কর্ম।', 'work; task', ['কর্ম', 'শ্রম'], ['আমার অনেক কাজ আছে।', 'I have a lot of work.']],
  ['somoy', 'সময়', 'somoy', 'noun', 'ʃomoj', 'ঘটনার ধারাবাহিক পরিমাপ।', 'time', ['কাল', 'বেলা'], ['সময় নষ্ট কোরো না।', 'Do not waste time.']],
  ['din', 'দিন', 'din', 'noun', 'din', 'সূর্যোদয় থেকে সূর্যাস্ত পর্যন্ত সময়।', 'day', ['দিবস', 'বার'], ['আজকের দিনটি সুন্দর।', 'Today is a beautiful day.']],
  ['rat', 'রাত', 'rat', 'noun', 'rat', 'সূর্যাস্ত থেকে সূর্যোদয় পর্যন্ত অন্ধকার সময়।', 'night', ['রজনী', 'নিশি'], ['রাতে আকাশে তারা দেখা যায়।', 'Stars are visible in the sky at night.']],
  ['sokal', 'সকাল', 'sokal', 'noun', 'ʃokal', 'দিনের প্রথম ভাগ।', 'morning', ['প্রভাত', 'ভোর'], ['সকালে হাঁটা ভালো।', 'Walking in the morning is good.']],
  ['bikel', 'বিকেল', 'bikel', 'noun', 'bikel', 'দুপুরের পর সন্ধ্যার আগের সময়।', 'afternoon', ['অপরাহ্ন'], ['বিকেলে আমরা খেলি।', 'We play in the afternoon.']],
  ['bochhor', 'বছর', 'bochhor', 'noun', 'botʃʰor', 'বারো মাসের সময়কাল।', 'year', ['বর্ষ', 'সন'], ['নতুন বছর শুরু হয়েছে।', 'The new year has begun.']],
  ['khabar', 'খাবার', 'khabar', 'noun', 'kʰabar', 'যা খাওয়া হয়।', 'food', ['আহার', 'খাদ্য'], ['খাবার গরম আছে।', 'The food is hot.']],
  ['bhat', 'ভাত', 'bhat', 'noun', 'bʱat', 'সেদ্ধ চাল, প্রধান খাদ্য।', 'cooked rice', ['অন্ন'], ['দুপুরে ভাত খাই।', 'I eat rice at noon.']],
  ['dudh', 'দুধ', 'dudh', 'noun', 'dudʱ', 'গবাদি পশু থেকে পাওয়া সাদা পুষ্টিকর তরল।', 'milk', ['ক্ষীর'], ['শিশু দুধ পান করে।', 'The child drinks milk.']],
  ['dim', 'ডিম', 'dim', 'noun', 'dim', 'পাখি বা মুরগির খোলাযুক্ত প্রজননকোষ।', 'egg', ['অণ্ড'], ['সকালে ডিম খেলাম।', 'I ate an egg in the morning.']],
  ['fol', 'ফল', 'fol', 'noun', 'fɔl', 'গাছের ভোজ্য মিষ্টি অংশ।', 'fruit', ['ফলমূল'], ['আম একটি মিষ্টি ফল।', 'The mango is a sweet fruit.']],
  ['am', 'আম', 'am', 'noun', 'am', 'গ্রীষ্মকালীন রসালো মিষ্টি ফল।', 'mango', ['আম্র'], ['গ্রীষ্মে আম পাকে।', 'Mangoes ripen in summer.']],
  ['kola', 'কলা', 'kola', 'noun', 'kola', 'লম্বাটে হলুদ খোসাযুক্ত মিষ্টি ফল।', 'banana', ['রম্ভা'], ['বাঁদর কলা খায়।', 'The monkey eats a banana.']],
  ['chaal', 'চাল', 'chaal', 'noun', 'tʃal', 'ধান থেকে পাওয়া শস্যদানা।', 'rice (uncooked)', ['তণ্ডুল'], ['বাজারে চালের দাম বেড়েছে।', 'The price of rice has risen in the market.']],
  ['nun', 'নুন', 'nun', 'noun', 'nun', 'রান্নায় ব্যবহৃত লবণাক্ত সাদা দানা।', 'salt', ['লবণ'], ['তরকারিতে নুন কম হয়েছে।', 'The curry has too little salt.']],
  ['chini', 'চিনি', 'chini', 'noun', 'tʃini', 'মিষ্টি স্বাদের সাদা দানা।', 'sugar', ['শর্করা'], ['চায়ে চিনি দাও।', 'Put sugar in the tea.']],
  ['cha', 'চা', 'cha', 'noun', 'tʃa', 'পাতা ফুটিয়ে তৈরি গরম পানীয়।', 'tea', [], ['সকালে এক কাপ চা খাই।', 'I drink a cup of tea in the morning.']],
  ['ranna', 'রান্না', 'ranna', 'noun', 'ranna', 'খাবার প্রস্তুত করার কাজ।', 'cooking', ['পাক'], ['মা রান্না করছেন।', 'Mother is cooking.']],
  ['bhalobasa', 'ভালোবাসা', 'bhalobasa', 'noun', 'bʱalobaʃa', 'গভীর স্নেহ ও অনুরাগ।', 'love', ['প্রেম', 'অনুরাগ'], ['ভালোবাসা মানুষকে কাছে টানে।', 'Love brings people close.']],
  ['ananda', 'আনন্দ', 'ananda', 'noun', 'anɔndo', 'সুখ ও খুশির অনুভূতি।', 'joy; happiness', ['সুখ', 'হর্ষ'], ['উৎসবে সবার মনে আনন্দ।', 'Everyone feels joy during the festival.']],
  ['dukkho', 'দুঃখ', 'dukkho', 'noun', 'dukkʰo', 'কষ্ট ও বেদনার অনুভূতি।', 'sorrow; grief', ['কষ্ট', 'বেদনা'], ['তার মনে অনেক দুঃখ।', 'There is much sorrow in his heart.']],
  ['bhoy', 'ভয়', 'bhoy', 'noun', 'bʱɔj', 'আশঙ্কা বা ভীতির অনুভূতি।', 'fear', ['ভীতি', 'শঙ্কা'], ['অন্ধকারে তার ভয় করে।', 'He feels fear in the dark.']],
  ['asha', 'আশা', 'asha', 'noun', 'aʃa', 'ভালো কিছু ঘটার প্রত্যাশা।', 'hope', ['প্রত্যাশা', 'ভরসা'], ['আশা কখনো হারিও না।', 'Never lose hope.']],
  ['shanti', 'শান্তি', 'shanti', 'noun', 'ʃanti', 'অস্থিরতাহীন স্থির অবস্থা।', 'peace', ['প্রশান্তি'], ['সবাই শান্তি চায়।', 'Everyone wants peace.']],
  ['bhasha', 'ভাষা', 'bhasha', 'noun', 'bʱaʃa', 'ভাব প্রকাশের শব্দ ও ধ্বনির ব্যবস্থা।', 'language', ['বুলি'], ['বাংলা আমার মাতৃভাষা।', 'Bangla is my mother tongue.']],
  ['bangla', 'বাংলা', 'bangla', 'noun', 'baŋla', 'বাঙালিদের ভাষা ও সংস্কৃতি।', 'Bangla; Bengali', [], ['আমি বাংলা ভালোবাসি।', 'I love Bangla.']],
  ['gaan', 'গান', 'gaan', 'noun', 'gan', 'সুরে গাওয়া কথা ও ধ্বনি।', 'song', ['সঙ্গীত', 'গীত'], ['সে সুন্দর গান গায়।', 'She sings beautiful songs.']],
  ['kobita', 'কবিতা', 'kobita', 'noun', 'kobita', 'ছন্দ ও ভাবে রচিত সাহিত্যরূপ।', 'poem; poetry', ['পদ্য', 'কাব্য'], ['সে একটি কবিতা লিখেছে।', 'He has written a poem.']],
  ['golpo', 'গল্প', 'golpo', 'noun', 'golpo', 'কল্পিত বা বাস্তব ঘটনার বিবরণ।', 'story', ['কাহিনি', 'আখ্যান'], ['দাদি রাতে গল্প বলেন।', 'Grandmother tells stories at night.']],
  ['chhobi', 'ছবি', 'chhobi', 'noun', 'tʃʰobi', 'রঙ ও রেখায় আঁকা দৃশ্য।', 'picture; image', ['চিত্র', 'প্রতিকৃতি'], ['দেয়ালে একটি ছবি টাঙানো।', 'A picture hangs on the wall.']],
  ['rong', 'রং', 'rong', 'noun', 'rɔŋ', 'বস্তুর দৃশ্যমান বর্ণ।', 'color', ['বর্ণ'], ['তার প্রিয় রং নীল।', 'His favorite color is blue.']],
  ['lal', 'লাল', 'lal', 'adjective', 'lal', 'রক্তের মতো বর্ণবিশিষ্ট।', 'red', ['রক্তবর্ণ'], ['তার একটি লাল জামা আছে।', 'She has a red dress.']],
  ['nil', 'নীল', 'nil', 'adjective', 'nil', 'আকাশ বা সমুদ্রের মতো বর্ণবিশিষ্ট।', 'blue', [], ['আকাশ নীল দেখায়।', 'The sky looks blue.']],
  ['shobuj', 'সবুজ', 'shobuj', 'adjective', 'ʃobudʒ', 'ঘাস বা পাতার মতো বর্ণবিশিষ্ট।', 'green', ['হরিৎ'], ['মাঠ সবুজ ঘাসে ঢাকা।', 'The field is covered in green grass.']],
  ['sada', 'সাদা', 'sada', 'adjective', 'ʃada', 'দুধ বা বরফের মতো বর্ণবিশিষ্ট।', 'white', ['শুভ্র', 'ধবল'], ['তার সাদা পোশাক পরিষ্কার।', 'His white clothes are clean.']],
  ['kalo', 'কালো', 'kalo', 'adjective', 'kalo', 'অন্ধকার বা কয়লার মতো বর্ণবিশিষ্ট।', 'black', ['কৃষ্ণ'], ['রাত কালো অন্ধকার।', 'The night is pitch black.']],
  ['boro', 'বড়', 'boro', 'adjective', 'bɔɽo', 'আকারে বা মাপে অধিক।', 'big; large', ['বৃহৎ', 'বিশাল'], ['এটি একটি বড় বাড়ি।', 'This is a big house.']],
  ['chhoto', 'ছোট', 'chhoto', 'adjective', 'tʃʰoto', 'আকারে বা মাপে কম।', 'small; little', ['ক্ষুদ্র'], ['তার একটি ছোট বিড়াল আছে।', 'She has a small cat.']],
  ['bhalo', 'ভালো', 'bhalo', 'adjective', 'bʱalo', 'গুণে বা মানে উত্তম।', 'good', ['উত্তম', 'সৎ'], ['সে খুব ভালো মানুষ।', 'He is a very good person.']],
  ['kharap', 'খারাপ', 'kharap', 'adjective', 'kʰarap', 'গুণে বা মানে মন্দ।', 'bad', ['মন্দ', 'অশুভ'], ['আজ আবহাওয়া খারাপ।', 'The weather is bad today.']],
  ['notun', 'নতুন', 'notun', 'adjective', 'notun', 'সম্প্রতি তৈরি বা আসা।', 'new', ['নব', 'নবীন'], ['সে একটি নতুন গাড়ি কিনেছে।', 'He has bought a new car.']],
  ['purono', 'পুরনো', 'purono', 'adjective', 'purono', 'দীর্ঘদিন ধরে থাকা বা ব্যবহৃত।', 'old', ['প্রাচীন', 'জীর্ণ'], ['এই বইটি অনেক পুরনো।', 'This book is very old.']],
  ['lomba', 'লম্বা', 'lomba', 'adjective', 'lɔmba', 'দৈর্ঘ্যে অধিক।', 'long; tall', ['দীর্ঘ'], ['সে দেখতে লম্বা।', 'He is tall.']],
  ['choto_khato', 'বেঁটে', 'bete', 'adjective', 'bɛʈe', 'উচ্চতায় কম।', 'short (in height)', ['খর্ব'], ['লোকটি একটু বেঁটে।', 'The man is a bit short.']],
  ['gorom', 'গরম', 'gorom', 'adjective', 'gɔrom', 'উচ্চ তাপমাত্রাযুক্ত।', 'hot; warm', ['উষ্ণ', 'তপ্ত'], ['গ্রীষ্মে আবহাওয়া গরম।', 'The weather is hot in summer.']],
  ['thanda', 'ঠান্ডা', 'thanda', 'adjective', 'ʈʰanda', 'নিম্ন তাপমাত্রাযুক্ত।', 'cold; cool', ['শীতল', 'হিম'], ['ঠান্ডা পানি খেতে ভালো।', 'Cold water is nice to drink.']],
  ['druto', 'দ্রুত', 'druto', 'adjective', 'druto', 'অধিক গতিসম্পন্ন।', 'fast; quick', ['ক্ষিপ্র', 'দ্রুতগামী'], ['ট্রেন দ্রুত চলে।', 'The train moves fast.']],
  ['dhire', 'ধীরে', 'dhire', 'adverb', 'dʱire', 'কম গতিতে; আস্তে।', 'slowly', ['আস্তে', 'মন্থর'], ['ধীরে ধীরে হাঁটো।', 'Walk slowly.']],
  ['unchu', 'উঁচু', 'unchu', 'adjective', 'ũtʃu', 'উপরের দিকে অধিক বিস্তৃত।', 'high; tall', ['উচ্চ'], ['পাহাড় খুব উঁচু।', 'The mountain is very high.']],
  ['nichu', 'নিচু', 'nichu', 'adjective', 'nitʃu', 'নিচের দিকে অবস্থিত; কম উঁচু।', 'low', ['নিম্ন'], ['জায়গাটি একটু নিচু।', 'The place is a bit low.']],
  ['khola', 'খোলা', 'khola', 'adjective', 'kʰola', 'বন্ধ নয় এমন; উন্মুক্ত।', 'open', ['উন্মুক্ত'], ['দরজা খোলা আছে।', 'The door is open.']],
  ['bondho', 'বন্ধ', 'bondho', 'adjective', 'bɔndʱo', 'খোলা নয় এমন; রুদ্ধ।', 'closed; shut', ['রুদ্ধ'], ['দোকান আজ বন্ধ।', 'The shop is closed today.']],
  ['jawa', 'যাওয়া', 'jawa', 'verb', 'dʒaoa', 'এক স্থান থেকে অন্য স্থানে সরে যাওয়া।', 'to go', ['গমন করা'], ['আমাকে এখন যেতে হবে।', 'I have to go now.']],
  ['asha_v', 'আসা', 'asha', 'verb', 'aʃa', 'কোনো স্থানে পৌঁছানো বা আগমন করা।', 'to come', ['আগমন করা'], ['সে কাল আসবে।', 'He will come tomorrow.']],
  ['khawa', 'খাওয়া', 'khawa', 'verb', 'kʰaoa', 'খাদ্য গ্রহণ করা।', 'to eat', ['ভক্ষণ করা'], ['আমরা একসঙ্গে খাব।', 'We will eat together.']],
  ['pora', 'পড়া', 'pora', 'verb', 'pɔɽa', 'লেখা বুঝে পাঠ করা; অধ্যয়ন করা।', 'to read; to study', ['অধ্যয়ন করা'], ['সে বই পড়ছে।', 'She is reading a book.']],
  ['lekha', 'লেখা', 'lekha', 'verb', 'lekʰa', 'কলম বা যন্ত্রে শব্দ অঙ্কন করা।', 'to write', ['রচনা করা'], ['সে চিঠি লিখছে।', 'He is writing a letter.']],
  ['bola', 'বলা', 'bola', 'verb', 'bɔla', 'কথা প্রকাশ করা; উচ্চারণ করা।', 'to say; to speak', ['কহা'], ['সত্য কথা বলো।', 'Speak the truth.']],
  ['shona', 'শোনা', 'shona', 'verb', 'ʃona', 'কান দিয়ে ধ্বনি গ্রহণ করা।', 'to hear; to listen', ['শ্রবণ করা'], ['গান শুনতে ভালো লাগে।', 'I like listening to songs.']],
  ['dekha', 'দেখা', 'dekha', 'verb', 'dɛkʰa', 'চোখ দিয়ে অনুভব করা।', 'to see; to look', ['দর্শন করা'], ['আকাশ দেখো কত সুন্দর।', 'Look how beautiful the sky is.']],
  ['kora', 'করা', 'kora', 'verb', 'kɔra', 'কোনো কাজ সম্পন্ন করা।', 'to do; to make', ['সম্পাদন করা'], ['কাজটি ঠিকমতো করো।', 'Do the task properly.']],
  ['deoa', 'দেওয়া', 'deoa', 'verb', 'dɛoa', 'কিছু হাতে তুলে দেওয়া বা প্রদান করা।', 'to give', ['প্রদান করা'], ['আমাকে বইটি দাও।', 'Give me the book.']],
  ['neoa', 'নেওয়া', 'neoa', 'verb', 'nɛoa', 'কিছু গ্রহণ করা বা নিজের কাছে রাখা।', 'to take', ['গ্রহণ করা'], ['ছাতাটি সঙ্গে নাও।', 'Take the umbrella with you.']],
  ['ghumano', 'ঘুমানো', 'ghumano', 'verb', 'gʱumano', 'নিদ্রা যাওয়া; বিশ্রাম নেওয়া।', 'to sleep', ['নিদ্রা যাওয়া'], ['শিশু ঘুমাচ্ছে।', 'The baby is sleeping.']],
  ['hasha', 'হাসা', 'hasha', 'verb', 'haʃa', 'আনন্দে মুখে হাসি প্রকাশ করা।', 'to laugh; to smile', [], ['সে মন খুলে হাসে।', 'She laughs heartily.']],
  ['kanna', 'কান্না', 'kanna', 'noun', 'kanna', 'দুঃখে বা কষ্টে চোখের জল ফেলা।', 'crying; weeping', ['ক্রন্দন'], ['শিশুর কান্না থামছে না।', 'The baby will not stop crying.']],
  ['hata', 'হাঁটা', 'hata', 'verb', 'hãʈa', 'পায়ে হেঁটে চলা।', 'to walk', ['পদব্রজে চলা'], ['সকালে হাঁটা স্বাস্থ্যকর।', 'Walking in the morning is healthy.']],
  ['dourano', 'দৌড়ানো', 'dourano', 'verb', 'douɽano', 'দ্রুত গতিতে পায়ে চলা।', 'to run', ['ধাবন করা'], ['সে মাঠে দৌড়াচ্ছে।', 'He is running in the field.']],
  ['khela', 'খেলা', 'khela', 'noun', 'kʰɛla', 'বিনোদন বা প্রতিযোগিতার কাজ।', 'game; play', ['ক্রীড়া'], ['শিশুরা খেলা করছে।', 'The children are playing.']],
  ['kaj_kora', 'পরিশ্রম', 'porishrom', 'noun', 'poriʃrom', 'কঠোর মেহনত বা খাটুনি।', 'hard work; labor', ['মেহনত', 'শ্রম'], ['পরিশ্রমে সফলতা আসে।', 'Success comes through hard work.']],
  ['taka', 'টাকা', 'taka', 'noun', 'ʈaka', 'বাংলাদেশের মুদ্রা; অর্থ।', 'money; taka', ['অর্থ', 'মুদ্রা'], ['তার কাছে অনেক টাকা।', 'He has a lot of money.']],
  ['bajar', 'বাজার', 'bajar', 'noun', 'badʒar', 'যেখানে জিনিস কেনাবেচা হয়।', 'market', ['হাট'], ['মা বাজারে গেছেন।', 'Mother has gone to the market.']],
  ['dokan', 'দোকান', 'dokan', 'noun', 'dokan', 'যেখানে পণ্য বিক্রি হয়।', 'shop; store', ['বিপণি'], ['দোকানে নতুন জিনিস এসেছে।', 'New items have arrived at the shop.']],
  ['gari', 'গাড়ি', 'gari', 'noun', 'gaɽi', 'চাকাযুক্ত যানবাহন।', 'car; vehicle', ['যান', 'বাহন'], ['গাড়ি রাস্তায় চলছে।', 'The car is moving on the road.']],
  ['train', 'ট্রেন', 'tren', 'noun', 'ʈren', 'রেললাইনে চলা দীর্ঘ যান।', 'train', ['রেলগাড়ি'], ['ট্রেন সময়মতো এসেছে।', 'The train arrived on time.']],
  ['nouka', 'নৌকা', 'nouka', 'noun', 'nouka', 'জলে চলার ছোট যান।', 'boat', ['তরি', 'ডিঙি'], ['নৌকা নদীতে ভাসছে।', 'The boat floats on the river.']],
  ['hat', 'হাত', 'hat', 'noun', 'hat', 'শরীরের যে অঙ্গ দিয়ে ধরা হয়।', 'hand', ['কর', 'পাণি'], ['হাত ধুয়ে খাও।', 'Wash your hands before eating.']],
  ['pa', 'পা', 'pa', 'noun', 'pa', 'শরীরের যে অঙ্গ দিয়ে হাঁটা হয়।', 'foot; leg', ['চরণ', 'পদ'], ['তার পায়ে ব্যথা।', 'His foot hurts.']],
  ['chokh', 'চোখ', 'chokh', 'noun', 'tʃokʰ', 'শরীরের যে অঙ্গ দিয়ে দেখা হয়।', 'eye', ['নয়ন', 'আঁখি'], ['তার চোখ দুটি সুন্দর।', 'Her eyes are beautiful.']],
  ['kan', 'কান', 'kan', 'noun', 'kan', 'শরীরের যে অঙ্গ দিয়ে শোনা হয়।', 'ear', ['কর্ণ', 'শ্রবণ'], ['কান দিয়ে শব্দ শুনি।', 'We hear sound with our ears.']],
  ['mukh', 'মুখ', 'mukh', 'noun', 'mukʰ', 'মুখমণ্ডল; কথা বলার অঙ্গ।', 'face; mouth', ['বদন', 'আনন'], ['তার মুখে হাসি।', 'There is a smile on his face.']],
  ['matha', 'মাথা', 'matha', 'noun', 'matʰa', 'শরীরের উপরের অংশ; মস্তক।', 'head', ['মস্তক', 'শির'], ['তার মাথা ব্যথা করছে।', 'His head is aching.']],
  ['mon', 'মন', 'mon', 'noun', 'mɔn', 'চিন্তা ও অনুভূতির কেন্দ্র।', 'mind; heart', ['চিত্ত', 'হৃদয়'], ['তার মন আজ খুশি।', 'His mind is happy today.']],
  ['gyan', 'জ্ঞান', 'gyan', 'noun', 'ggæn', 'জানা ও বোঝার ক্ষমতা।', 'knowledge', ['বিদ্যা', 'প্রজ্ঞা'], ['জ্ঞান মানুষকে আলোকিত করে।', 'Knowledge enlightens people.']],
  ['shotto', 'সত্য', 'shotto', 'noun', 'ʃotto', 'যা সঠিক ও বাস্তব।', 'truth', ['যথার্থ'], ['সত্য কখনো লুকায় না।', 'Truth never stays hidden.']],
  ['mittha', 'মিথ্যা', 'mittha', 'noun', 'mittʰa', 'যা সত্য নয়; অসত্য।', 'lie; falsehood', ['অসত্য'], ['মিথ্যা বলা উচিত নয়।', 'One should not tell lies.']],
  ['shopno', 'স্বপ্ন', 'shopno', 'noun', 'ʃɔpno', 'ঘুমের মধ্যে দেখা দৃশ্য; আকাঙ্ক্ষা।', 'dream', [], ['তার একটি বড় স্বপ্ন আছে।', 'He has a big dream.']],
  ['prithibi', 'পৃথিবী', 'prithibi', 'noun', 'pritʰibi', 'আমরা যে গ্রহে বাস করি।', 'earth; world', ['ধরা', 'বসুন্ধরা'], ['পৃথিবী সূর্যের চারদিকে ঘোরে।', 'The earth revolves around the sun.']],
  ['brishti', 'বৃষ্টি', 'brishti', 'noun', 'briʃʈi', 'মেঘ থেকে পড়া জল।', 'rain', ['বর্ষণ'], ['বৃষ্টিতে মাটি ভিজে গেছে।', 'The soil is wet from the rain.']],
  ['megh', 'মেঘ', 'megh', 'noun', 'megʱ', 'আকাশে জমা জলীয় বাষ্প।', 'cloud', ['জলধর'], ['আকাশে কালো মেঘ জমেছে।', 'Dark clouds have gathered in the sky.']],
  ['shishu', 'শিশু', 'shishu', 'noun', 'ʃiʃu', 'ছোট বয়সের বাচ্চা।', 'child; baby', ['বাচ্চা', 'শাবক'], ['শিশুটি হাসছে।', 'The baby is smiling.']],
  ['bura', 'বৃদ্ধ', 'briddho', 'adjective', 'briddʱo', 'বয়সে প্রবীণ।', 'old (person); elderly', ['প্রবীণ'], ['বৃদ্ধ লোকটি ধীরে হাঁটেন।', 'The old man walks slowly.']],
  ['jibon', 'জীবন', 'jibon', 'noun', 'dʒibon', 'বেঁচে থাকার অবস্থা।', 'life', ['প্রাণ', 'আয়ু'], ['জীবন খুব মূল্যবান।', 'Life is very precious.']],
  ['mrittu', 'মৃত্যু', 'mrittu', 'noun', 'mrittu', 'জীবনের অবসান।', 'death', ['মরণ'], ['মৃত্যু জীবনের অনিবার্য সত্য।', 'Death is the inevitable truth of life.']],
  ['shorir', 'শরীর', 'shorir', 'noun', 'ʃorir', 'প্রাণীর দেহ।', 'body', ['দেহ', 'কায়া'], ['ব্যায়ামে শরীর সুস্থ থাকে।', 'Exercise keeps the body healthy.']],
  ['rog', 'রোগ', 'rog', 'noun', 'rog', 'শরীরের অসুস্থ অবস্থা।', 'disease; illness', ['ব্যাধি', 'অসুখ'], ['সময়মতো রোগের চিকিৎসা দরকার।', 'A disease needs timely treatment.']],
  ['oushudh', 'ওষুধ', 'oushudh', 'noun', 'ouʃudʱ', 'রোগ সারাতে ব্যবহৃত দ্রব্য।', 'medicine', ['ঔষধ', 'দাওয়াই'], ['ডাক্তার ওষুধ দিয়েছেন।', 'The doctor has given medicine.']],
  ['alo', 'আলো', 'alo', 'noun', 'alo', 'যা দিয়ে দেখা যায়; দীপ্তি।', 'light', ['জ্যোতি', 'দীপ্তি'], ['ঘরে আলো জ্বলছে।', 'The light is on in the room.']],
  ['andhokar', 'অন্ধকার', 'andhokar', 'noun', 'ɔndʱokar', 'আলোর অভাব।', 'darkness', ['তমসা', 'আঁধার'], ['রাতে চারদিকে অন্ধকার।', 'It is dark all around at night.']],
  ['shokti', 'শক্তি', 'shokti', 'noun', 'ʃokti', 'কাজ করার সামর্থ্য বা বল।', 'power; strength; energy', ['বল', 'ক্ষমতা'], ['সূর্য থেকে শক্তি পাওয়া যায়।', 'Energy is obtained from the sun.']],
  ['shomoy_shuchi', 'ইতিহাস', 'itihas', 'noun', 'itihaʃ', 'অতীত ঘটনার লিখিত বিবরণ।', 'history', ['পুরাবৃত্ত'], ['আমরা দেশের ইতিহাস পড়ি।', 'We study the history of the country.']],
  ['bigyan', 'বিজ্ঞান', 'bigyan', 'noun', 'biggæn', 'পর্যবেক্ষণ ও পরীক্ষার মাধ্যমে অর্জিত জ্ঞান।', 'science', [], ['বিজ্ঞান আমাদের জীবন সহজ করেছে।', 'Science has made our lives easier.']],
  ['ganit', 'গণিত', 'ganit', 'noun', 'gonit', 'সংখ্যা ও পরিমাণ নিয়ে বিদ্যা।', 'mathematics', ['অঙ্কশাস্ত্র'], ['গণিত আমার প্রিয় বিষয়।', 'Mathematics is my favorite subject.']],
  ['kolom', 'কলম', 'kolom', 'noun', 'kɔlom', 'লেখার জন্য কালিভরা যন্ত্র।', 'pen', ['লেখনী'], ['কলম দিয়ে লিখি।', 'I write with a pen.']],
  ['kagoj', 'কাগজ', 'kagoj', 'noun', 'kagodʒ', 'লেখা ও ছাপার পাতলা উপাদান।', 'paper', ['পত্র'], ['কাগজে ছবি আঁকি।', 'I draw a picture on paper.']],
  ['darja', 'দরজা', 'darja', 'noun', 'dɔrdʒa', 'ঘরে ঢোকার মুখ।', 'door', ['কপাট', 'দ্বার'], ['দরজাটি বন্ধ করো।', 'Close the door.']],
  ['janala', 'জানালা', 'janala', 'noun', 'dʒanala', 'ঘরের যে ফাঁক দিয়ে আলো-বাতাস আসে।', 'window', ['বাতায়ন', 'গবাক্ষ'], ['জানালা দিয়ে বাতাস আসে।', 'Air comes in through the window.']],
  ['bichana', 'বিছানা', 'bichana', 'noun', 'bitʃana', 'ঘুমানোর জন্য পাতা শয্যা।', 'bed', ['শয্যা'], ['সে বিছানায় শুয়ে আছে।', 'She is lying on the bed.']],
  ['jama', 'জামা', 'jama', 'noun', 'dʒama', 'শরীরে পরিধেয় পোশাক।', 'shirt; clothes', ['বস্ত্র', 'পোশাক'], ['তার নতুন জামা পছন্দ হয়েছে।', 'He liked his new shirt.']],
  ['juta', 'জুতা', 'juta', 'noun', 'dʒuta', 'পায়ে পরার আবরণ।', 'shoe', ['পাদুকা'], ['জুতা পরে বাইরে যাও।', 'Wear shoes when going out.']],
  ['ghori', 'ঘড়ি', 'ghori', 'noun', 'gʱoɽi', 'সময় দেখার যন্ত্র।', 'clock; watch', ['সময়যন্ত্র'], ['ঘড়িতে এখন দশটা।', 'It is ten o clock now.']],
  ['chabi', 'চাবি', 'chabi', 'noun', 'tʃabi', 'তালা খোলা ও বন্ধ করার যন্ত্র।', 'key', ['কুঞ্চিকা'], ['দরজার চাবি হারিয়ে গেছে।', 'The door key is lost.']],
  ['ayna', 'আয়না', 'ayna', 'noun', 'ajna', 'যে কাঁচে নিজের প্রতিবিম্ব দেখা যায়।', 'mirror', ['দর্পণ'], ['আয়নায় নিজেকে দেখি।', 'I look at myself in the mirror.']],
  ['bidyut', 'বিদ্যুৎ', 'bidyut', 'noun', 'biddut', 'তড়িৎ শক্তি।', 'electricity', ['তড়িৎ', 'বিজলি'], ['বিদ্যুৎ চলে গেছে।', 'The electricity has gone out.']],
  ['agni', 'তাপ', 'tap', 'noun', 'tap', 'গরম হওয়ার অনুভূতি বা শক্তি।', 'heat', ['উত্তাপ'], ['সূর্যের তাপ প্রখর।', 'The heat of the sun is intense.']],
  ['borsha', 'বর্ষা', 'borsha', 'noun', 'bɔrʃa', 'বৃষ্টিবহুল ঋতু।', 'monsoon; rainy season', [], ['বর্ষায় নদী ভরে ওঠে।', 'Rivers fill up during the monsoon.']],
  ['shirt_kal', 'শীত', 'shit', 'noun', 'ʃit', 'ঠান্ডা ঋতু।', 'winter', ['শীতকাল'], ['শীতে সবাই গরম কাপড় পরে।', 'Everyone wears warm clothes in winter.']],
  ['grishmo', 'গ্রীষ্ম', 'grishmo', 'noun', 'griʃʃo', 'গরম ঋতু।', 'summer', ['গ্রীষ্মকাল'], ['গ্রীষ্মে দিন বড় হয়।', 'Days are longer in summer.']],
  ['bosonto', 'বসন্ত', 'bosonto', 'noun', 'bɔʃonto', 'ফুল ফোটার ঋতু।', 'spring', [], ['বসন্তে গাছে নতুন পাতা আসে।', 'New leaves appear on trees in spring.']],
  ['desh', 'দেশ', 'desh', 'noun', 'deʃ', 'নির্দিষ্ট সীমানার ভূখণ্ড ও জাতি।', 'country', ['রাষ্ট্র', 'ভূখণ্ড'], ['আমি আমার দেশকে ভালোবাসি।', 'I love my country.']],
  ['manchitro', 'মানচিত্র', 'manchitro', 'noun', 'mantʃitro', 'ভূখণ্ডের অঙ্কিত চিত্র।', 'map', [], ['মানচিত্রে নদী দেখানো আছে।', 'The river is shown on the map.']],
  ['itihaser_boi', 'সংবাদ', 'shongbad', 'noun', 'ʃoŋbad', 'নতুন ঘটনার খবর।', 'news', ['খবর', 'বার্তা'], ['সকালে সংবাদ পড়ি।', 'I read the news in the morning.']],
  ['prosno', 'প্রশ্ন', 'proshno', 'noun', 'proʃno', 'উত্তর জানতে চাওয়া কথা।', 'question', ['জিজ্ঞাসা'], ['তার প্রশ্নের উত্তর দাও।', 'Answer his question.']],
  ['uttor', 'উত্তর', 'uttor', 'noun', 'uttor', 'প্রশ্নের জবাব; একটি দিক।', 'answer; north', ['জবাব'], ['তার উত্তর সঠিক ছিল।', 'His answer was correct.']],
  ['shomadhan', 'সমাধান', 'shomadhan', 'noun', 'ʃomadʱan', 'সমস্যার নিষ্পত্তি।', 'solution', ['নিষ্পত্তি'], ['সমস্যার সমাধান পাওয়া গেছে।', 'A solution to the problem has been found.']],
  ['shomossa', 'সমস্যা', 'shomossa', 'noun', 'ʃomoʃʃa', 'যা সমাধান করা প্রয়োজন।', 'problem', ['ঝামেলা'], ['এটি একটি কঠিন সমস্যা।', 'This is a difficult problem.']],
  ['shongkhya', 'সংখ্যা', 'shongkhya', 'noun', 'ʃoŋkʰæ', 'গণনার একক; নম্বর।', 'number', ['নম্বর', 'অঙ্ক'], ['পাঁচ একটি ছোট সংখ্যা।', 'Five is a small number.']],
  ['nam', 'নাম', 'nam', 'noun', 'nam', 'পরিচয়ের জন্য দেওয়া শব্দ।', 'name', ['অভিধা'], ['তার নাম কী?', 'What is his name?']],
  ['kotha', 'কথা', 'kotha', 'noun', 'kɔtʰa', 'উচ্চারিত বা লিখিত বাক্য।', 'word; talk', ['বাণী', 'বাক্য'], ['তার কথা সবাই শোনে।', 'Everyone listens to what he says.']],
  ['chithi', 'চিঠি', 'chithi', 'noun', 'tʃiʈʰi', 'লিখিত বার্তা যা পাঠানো হয়।', 'letter', ['পত্র'], ['সে বন্ধুকে চিঠি লিখেছে।', 'He has written a letter to his friend.']],
  ['upohar', 'উপহার', 'upohar', 'noun', 'upohar', 'ভালোবাসা বা সম্মানে দেওয়া জিনিস।', 'gift; present', ['উপঢৌকন'], ['সে আমাকে উপহার দিয়েছে।', 'She has given me a gift.']],
  ['utsob', 'উৎসব', 'utsob', 'noun', 'utʃʃɔb', 'আনন্দের সামাজিক অনুষ্ঠান।', 'festival', ['পার্বণ'], ['গ্রামে উৎসব চলছে।', 'A festival is going on in the village.']],
  ['bijoy', 'বিজয়', 'bijoy', 'noun', 'bidʒoj', 'জয় বা সাফল্য।', 'victory', ['জয়', 'বিজয়লাভ'], ['দলটি বিজয় অর্জন করেছে।', 'The team has achieved victory.']],
  ['shadhinota', 'স্বাধীনতা', 'shadhinota', 'noun', 'ʃadʱinota', 'পরাধীনতা থেকে মুক্ত অবস্থা।', 'freedom; independence', ['মুক্তি'], ['স্বাধীনতা সবার অধিকার।', 'Freedom is everyone right.']],
  ['nyay', 'ন্যায়', 'nyay', 'noun', 'næj', 'সঠিক ও সুবিচারপূর্ণ আচরণ।', 'justice', ['সুবিচার'], ['বিচারক ন্যায় প্রতিষ্ঠা করেন।', 'The judge establishes justice.']],
  ['shahajjo', 'সাহায্য', 'shahajjo', 'noun', 'ʃahaddʒo', 'অন্যকে সহযোগিতা করা।', 'help; aid', ['সহযোগিতা', 'উপকার'], ['বিপদে বন্ধুর সাহায্য পেয়েছি।', 'I got my friend help in trouble.']],
  ['bishwas', 'বিশ্বাস', 'bishwas', 'noun', 'biʃʃaʃ', 'কারও বা কিছুর প্রতি আস্থা।', 'trust; belief', ['আস্থা', 'ভরসা'], ['তার প্রতি আমার বিশ্বাস আছে।', 'I have trust in him.']],
  ['shomman', 'সম্মান', 'shomman', 'noun', 'ʃomman', 'শ্রদ্ধা ও মর্যাদা।', 'respect; honor', ['শ্রদ্ধা', 'মর্যাদা'], ['বড়দের সম্মান করা উচিত।', 'One should respect elders.']],

  // --- Expansion batch (WordSetu 0.2.0): additional original CC0 vocabulary ---
  // Numbers.
  ['ek', 'এক', 'ek', 'number', 'æk', 'গণনার প্রথম সংখ্যা; ১।', 'one', [], ['আমার কাছে এক টাকা আছে।', 'I have one taka.']],
  ['dui', 'দুই', 'dui', 'number', 'dui', 'গণনার দ্বিতীয় সংখ্যা; ২।', 'two', [], ['তার দুই ভাই।', 'He has two brothers.']],
  ['tin', 'তিন', 'tin', 'number', 'tin', 'গণনার তৃতীয় সংখ্যা; ৩।', 'three', [], ['তিন দিন পরে দেখা হবে।', 'We will meet after three days.']],
  ['char', 'চার', 'char', 'number', 'tʃar', 'গণনার চতুর্থ সংখ্যা; ৪।', 'four', [], ['টেবিলে চার পা আছে।', 'The table has four legs.']],
  ['panch', 'পাঁচ', 'panch', 'number', 'pãtʃ', 'গণনার পঞ্চম সংখ্যা; ৫।', 'five', [], ['তার হাতে পাঁচ আঙুল।', 'There are five fingers on his hand.']],
  ['choy', 'ছয়', 'choy', 'number', 'tʃɔj', 'গণনার ষষ্ঠ সংখ্যা; ৬।', 'six', [], ['ছয় মাস কেটে গেছে।', 'Six months have passed.']],
  ['shat', 'সাত', 'shat', 'number', 'ʃat', 'গণনার সপ্তম সংখ্যা; ৭।', 'seven', [], ['সপ্তাহে সাত দিন।', 'There are seven days in a week.']],
  ['at', 'আট', 'at', 'number', 'aʈ', 'গণনার অষ্টম সংখ্যা; ৮।', 'eight', [], ['আট ঘণ্টা কাজ করি।', 'I work eight hours.']],
  ['noy', 'নয়', 'noy', 'number', 'nɔj', 'গণনার নবম সংখ্যা; ৯।', 'nine', [], ['নয় জন খেলোয়াড় এসেছে।', 'Nine players have come.']],
  ['dosh', 'দশ', 'dosh', 'number', 'dɔʃ', 'গণনার দশম সংখ্যা; ১০।', 'ten', [], ['দশ টাকা দাও।', 'Give me ten taka.']],
  ['sho', 'একশো', 'eksho', 'number', 'ækʃo', 'দশ গুণ দশ; ১০০।', 'hundred', ['শত'], ['একশো বছর আগের কথা।', 'This is a story of a hundred years ago.']],
  ['hajar', 'হাজার', 'hajar', 'number', 'hadʒar', 'দশ গুণ একশো; ১০০০।', 'thousand', [], ['হাজার মানুষ জড়ো হয়েছে।', 'A thousand people have gathered.']],

  // Kinship.
  ['dada', 'দাদা', 'dada', 'noun', 'dada', 'বড় ভাই বা পিতামহ।', 'elder brother; grandfather', ['অগ্রজ'], ['দাদা আমাকে খুব স্নেহ করেন।', 'My elder brother loves me dearly.']],
  ['didi', 'দিদি', 'didi', 'noun', 'didi', 'বড় বোন।', 'elder sister', ['অগ্রজা'], ['দিদি রান্না শেখাচ্ছেন।', 'Elder sister is teaching cooking.']],
  ['dadu', 'দাদু', 'dadu', 'noun', 'dadu', 'পিতামহ বা মাতামহ; বৃদ্ধ আত্মীয়।', 'grandfather', ['ঠাকুরদা'], ['দাদু গল্প বলেন।', 'Grandfather tells stories.']],
  ['thakuma', 'ঠাকুমা', 'thakuma', 'noun', 'ʈʰakuma', 'পিতার মা; পিতামহী।', 'grandmother', ['দিদিমা'], ['ঠাকুমা পিঠা বানান।', 'Grandmother makes cakes.']],
  ['kaka', 'কাকা', 'kaka', 'noun', 'kaka', 'পিতার ছোট ভাই।', 'uncle (paternal)', ['চাচা'], ['কাকা গ্রামে থাকেন।', 'Uncle lives in the village.']],
  ['mama', 'মামা', 'mama', 'noun', 'mama', 'মায়ের ভাই।', 'uncle (maternal)', [], ['মামা শহর থেকে এসেছেন।', 'Maternal uncle has come from the city.']],
  ['pishi', 'পিসি', 'pishi', 'noun', 'piʃi', 'পিতার বোন।', 'aunt (paternal)', ['ফুপু'], ['পিসি আমাকে উপহার দিলেন।', 'Aunt gave me a gift.']],
  ['mashi', 'মাসি', 'mashi', 'noun', 'maʃi', 'মায়ের বোন।', 'aunt (maternal)', ['খালা'], ['মাসির বাড়ি যাচ্ছি।', 'I am going to my aunt house.']],
  ['stri', 'স্ত্রী', 'stri', 'noun', 'stri', 'বিবাহিত নারী সঙ্গিনী।', 'wife', ['বউ', 'পত্নী'], ['তার স্ত্রী শিক্ষক।', 'His wife is a teacher.']],
  ['shami', 'স্বামী', 'shami', 'noun', 'ʃami', 'বিবাহিত পুরুষ সঙ্গী।', 'husband', ['বর', 'পতি'], ['তার স্বামী ব্যবসায়ী।', 'Her husband is a businessman.']],
  ['chele_shontan', 'সন্তান', 'shontan', 'noun', 'ʃɔntan', 'কারও ছেলে বা মেয়ে।', 'child; offspring', ['ছানা'], ['তাদের দুটি সন্তান।', 'They have two children.']],
  ['atmiyo', 'আত্মীয়', 'atmiyo', 'noun', 'attio', 'রক্ত বা বিবাহসূত্রে সম্পর্কিত ব্যক্তি।', 'relative', ['স্বজন'], ['উৎসবে আত্মীয়রা আসেন।', 'Relatives come during the festival.']],
  ['protibeshi', 'প্রতিবেশী', 'protibeshi', 'noun', 'protibeʃi', 'পাশে বসবাসকারী ব্যক্তি।', 'neighbor', ['পড়শি'], ['প্রতিবেশী খুব ভালো।', 'The neighbor is very nice.']],

  // Body parts.
  ['nak', 'নাক', 'nak', 'noun', 'nak', 'শ্বাস নেওয়া ও গন্ধ নেওয়ার অঙ্গ।', 'nose', ['নাসিকা'], ['ফুলের গন্ধ নাকে আসে।', 'The scent of flowers reaches the nose.']],
  ['dat', 'দাঁত', 'dat', 'noun', 'dãt', 'মুখের ভেতরের শক্ত চিবানোর অঙ্গ।', 'tooth', ['দন্ত'], ['প্রতিদিন দাঁত মাজা উচিত।', 'One should brush teeth every day.']],
  ['jib', 'জিভ', 'jib', 'noun', 'dʒib', 'মুখের ভেতরের স্বাদ নেওয়ার অঙ্গ।', 'tongue', ['জিহ্বা'], ['জিভ দিয়ে স্বাদ বুঝি।', 'We taste with the tongue.']],
  ['gola', 'গলা', 'gola', 'noun', 'gɔla', 'মাথা ও ধড়ের সংযোগস্থল; কণ্ঠ।', 'throat; neck', ['কণ্ঠ', 'গ্রীবা'], ['তার গলা ব্যথা করছে।', 'His throat hurts.']],
  ['angul', 'আঙুল', 'angul', 'noun', 'aŋul', 'হাত বা পায়ের সরু অংশ।', 'finger', ['অঙ্গুলি'], ['আঙুলে আংটি পরেছে।', 'She wears a ring on her finger.']],
  ['chul', 'চুল', 'chul', 'noun', 'tʃul', 'মাথায় গজানো সরু তন্তু।', 'hair', ['কেশ'], ['তার লম্বা কালো চুল।', 'She has long black hair.']],
  ['bhuru', 'ভ্রু', 'bhuru', 'noun', 'bʱru', 'চোখের উপরের লোমরেখা।', 'eyebrow', [], ['সে ভ্রু কুঁচকে তাকাল।', 'He looked with a frown.']],
  ['thot', 'ঠোঁট', 'thot', 'noun', 'ʈʰõʈ', 'মুখের বাইরের নরম প্রান্ত।', 'lip', ['অধর'], ['তার ঠোঁটে হাসি।', 'There is a smile on her lips.']],
  ['peth', 'পেট', 'peth', 'noun', 'peʈ', 'দেহের যে অংশে খাবার হজম হয়।', 'stomach; belly', ['উদর'], ['তার পেট ব্যথা করছে।', 'His stomach hurts.']],
  ['pith', 'পিঠ', 'pith', 'noun', 'piʈʰ', 'দেহের পশ্চাৎভাগ।', 'back', ['পৃষ্ঠ'], ['ভারী বোঝা পিঠে বইছে।', 'He carries a heavy load on his back.']],
  ['hridoy', 'হৃদয়', 'hridoy', 'noun', 'ridoj', 'রক্ত সঞ্চালনকারী অঙ্গ; আবেগের কেন্দ্র।', 'heart', ['হৃৎপিণ্ড'], ['তার হৃদয় দয়ায় ভরা।', 'His heart is full of kindness.']],
  ['rokto', 'রক্ত', 'rokto', 'noun', 'rɔkto', 'দেহের লাল তরল।', 'blood', ['শোণিত'], ['ক্ষত থেকে রক্ত ঝরছে।', 'Blood is flowing from the wound.']],
  ['haar', 'হাড়', 'haar', 'noun', 'haɽ', 'দেহের কাঠামো গঠনকারী শক্ত অংশ।', 'bone', ['অস্থি'], ['দুধ হাড় শক্ত করে।', 'Milk strengthens the bones.']],
  ['tok', 'ত্বক', 'tok', 'noun', 'tɔk', 'দেহের বাইরের আবরণ; চামড়া।', 'skin', ['চর্ম'], ['রোদে ত্বক পুড়ে যায়।', 'Skin burns in the sun.']],

  // Animals.
  ['bagh', 'বাঘ', 'bagh', 'noun', 'bagʱ', 'ডোরাকাটা বড় হিংস্র বিড়ালজাতীয় প্রাণী।', 'tiger', ['শার্দূল'], ['সুন্দরবনে বাঘ থাকে।', 'Tigers live in the Sundarbans.']],
  ['singho', 'সিংহ', 'singho', 'noun', 'ʃiŋho', 'বনের রাজা বলে পরিচিত হিংস্র প্রাণী।', 'lion', ['কেশরী'], ['সিংহ গর্জন করে।', 'The lion roars.']],
  ['hati', 'হাতি', 'hati', 'noun', 'hati', 'লম্বা শুঁড়যুক্ত বিশাল স্তন্যপায়ী।', 'elephant', ['গজ', 'করী'], ['হাতি শুঁড় দিয়ে জল নেয়।', 'The elephant takes water with its trunk.']],
  ['ghora', 'ঘোড়া', 'ghora', 'noun', 'gʱoɽa', 'দ্রুতগামী চার পায়ের বাহন পশু।', 'horse', ['অশ্ব', 'তুরগ'], ['ঘোড়া দ্রুত ছোটে।', 'The horse runs fast.']],
  ['goru', 'গরু', 'goru', 'noun', 'goru', 'দুধ ও কৃষিকাজে ব্যবহৃত গৃহপালিত পশু।', 'cow', ['গাভি', 'ধেনু'], ['গরু ঘাস খায়।', 'The cow eats grass.']],
  ['chagol', 'ছাগল', 'chagol', 'noun', 'tʃagol', 'ছোট শিংওয়ালা গৃহপালিত পশু।', 'goat', ['অজ'], ['ছাগল লাফ দিয়ে চলে।', 'The goat moves by jumping.']],
  ['kukur', 'কুকুর', 'kukur', 'noun', 'kukur', 'বিশ্বস্ত গৃহপালিত প্রাণী।', 'dog', ['সারমেয়'], ['কুকুর ঘর পাহারা দেয়।', 'The dog guards the house.']],
  ['biral', 'বিড়াল', 'biral', 'noun', 'biɽal', 'নরম লোমযুক্ত ছোট গৃহপালিত প্রাণী।', 'cat', ['মার্জার'], ['বিড়াল দুধ পছন্দ করে।', 'The cat likes milk.']],
  ['murgi', 'মুরগি', 'murgi', 'noun', 'murgi', 'ডিম ও মাংসের জন্য পালিত পাখি।', 'hen; chicken', ['কুক্কুট'], ['মুরগি ডিম পাড়ে।', 'The hen lays eggs.']],
  ['bandor', 'বাঁদর', 'bandor', 'noun', 'bãdor', 'গাছে লাফানো চঞ্চল প্রাণী।', 'monkey', ['বানর', 'কপি'], ['বাঁদর গাছে লাফায়।', 'The monkey jumps on trees.']],
  ['shap', 'সাপ', 'shap', 'noun', 'ʃap', 'পা ছাড়া লম্বা সরীসৃপ।', 'snake', ['সর্প', 'অহি'], ['ঘাসে একটি সাপ দেখলাম।', 'I saw a snake in the grass.']],
  ['bang', 'ব্যাঙ', 'bang', 'noun', 'bæŋ', 'জল ও ডাঙায় বাস করা লাফানো প্রাণী।', 'frog', ['ভেক', 'দাদুর'], ['বৃষ্টিতে ব্যাঙ ডাকে।', 'Frogs croak in the rain.']],
  ['prajapoti', 'প্রজাপতি', 'prajapoti', 'noun', 'prodʒapoti', 'রঙিন ডানাযুক্ত ছোট উড়ন্ত পতঙ্গ।', 'butterfly', [], ['ফুলে প্রজাপতি বসেছে।', 'A butterfly has landed on the flower.']],
  ['machhi', 'মাছি', 'machhi', 'noun', 'matʃʰi', 'ছোট বিরক্তিকর উড়ন্ত পতঙ্গ।', 'fly', ['মক্ষিকা'], ['খাবারে মাছি বসে।', 'A fly lands on the food.']],
  ['mohumachhi', 'মৌমাছি', 'mowmachhi', 'noun', 'mowmatʃʰi', 'মধু সংগ্রহকারী পতঙ্গ।', 'bee', ['ভ্রমর'], ['মৌমাছি মধু বানায়।', 'The bee makes honey.']],
  ['pipra', 'পিঁপড়া', 'pipra', 'noun', 'pĩpɽa', 'সারিবদ্ধ চলা ছোট পরিশ্রমী পতঙ্গ।', 'ant', ['পিপীলিকা'], ['পিঁপড়া খাবার বয়ে নেয়।', 'The ant carries food.']],

  // Nature and environment.
  ['pata', 'পাতা', 'pata', 'noun', 'pata', 'গাছের সবুজ চ্যাপ্টা অংশ।', 'leaf', ['পত্র', 'পল্লব'], ['শরতে পাতা ঝরে।', 'Leaves fall in autumn.']],
  ['shikor', 'শিকড়', 'shikor', 'noun', 'ʃikoɽ', 'গাছের মাটির নিচের অংশ।', 'root', ['মূল'], ['গাছের শিকড় গভীরে যায়।', 'The tree roots go deep.']],
  ['bij', 'বীজ', 'bij', 'noun', 'bidʒ', 'যা থেকে নতুন গাছ জন্মায়।', 'seed', ['বীচি'], ['মাটিতে বীজ পুঁতলাম।', 'I planted a seed in the soil.']],
  ['ghash', 'ঘাস', 'ghash', 'noun', 'gʱaʃ', 'মাটিতে জন্মানো সরু সবুজ উদ্ভিদ।', 'grass', ['তৃণ'], ['মাঠে সবুজ ঘাস।', 'There is green grass in the field.']],
  ['pathor', 'পাথর', 'pathor', 'noun', 'patʰor', 'শক্ত খনিজ পিণ্ড।', 'stone; rock', ['প্রস্তর', 'শিলা'], ['নদীর তীরে পাথর আছে।', 'There are stones by the river.']],
  ['balu', 'বালি', 'bali', 'noun', 'bali', 'সূক্ষ্ম দানাদার মাটি।', 'sand', ['বালুকা'], ['সৈকতে নরম বালি।', 'There is soft sand on the beach.']],
  ['dheu', 'ঢেউ', 'dheu', 'noun', 'ɖʱeu', 'জলের উঁচু-নিচু চলমান রেখা।', 'wave', ['তরঙ্গ'], ['সাগরে বড় ঢেউ ওঠে।', 'Big waves rise in the sea.']],
  ['borof', 'বরফ', 'borof', 'noun', 'bɔrof', 'জমে শক্ত হওয়া জল।', 'ice; snow', ['তুষার', 'হিম'], ['পাহাড়ে বরফ পড়ছে।', 'Snow is falling on the mountain.']],
  ['kuasha', 'কুয়াশা', 'kuasha', 'noun', 'kuaʃa', 'মাটির কাছে ভাসমান ঘন জলীয় বাষ্প।', 'fog; mist', ['নীহার'], ['শীতে ঘন কুয়াশা পড়ে।', 'Dense fog falls in winter.']],
  ['bidyut_chomok', 'বজ্র', 'bojro', 'noun', 'bɔdʒro', 'ঝড়ের সময় আকাশের প্রচণ্ড গর্জন।', 'thunder', ['অশনি'], ['বজ্রের শব্দে ভয় পেলাম।', 'I was scared by the thunder.']],
  ['jhor', 'ঝড়', 'jhor', 'noun', 'dʒʱɔɽ', 'প্রবল বাতাস ও বৃষ্টির প্রাকৃতিক ঘটনা।', 'storm', ['তুফান', 'ঝঞ্ঝা'], ['ঝড়ে গাছ ভেঙে পড়েছে।', 'A tree fell in the storm.']],
  ['rongdhonu', 'রংধনু', 'rongdhonu', 'noun', 'rɔŋdʱonu', 'বৃষ্টির পর আকাশে সাত রঙের বৃত্তচাপ।', 'rainbow', ['ইন্দ্রধনু'], ['বৃষ্টির পর রংধনু উঠেছে।', 'A rainbow appeared after the rain.']],
  ['maath', 'মাঠ', 'maath', 'noun', 'maʈʰ', 'খোলা সমতল জমি।', 'field', ['প্রান্তর'], ['ছেলেরা মাঠে খেলে।', 'The boys play in the field.']],
  ['pukur', 'পুকুর', 'pukur', 'noun', 'pukur', 'ছোট বদ্ধ জলাশয়।', 'pond', ['দিঘি', 'জলাশয়'], ['পুকুরে হাঁস সাঁতার কাটে।', 'Ducks swim in the pond.']],

  // Food and drink.
  ['ruti', 'রুটি', 'ruti', 'noun', 'ruti', 'আটা দিয়ে তৈরি সেঁকা খাবার।', 'bread; roti', [], ['সকালে রুটি খাই।', 'I eat bread in the morning.']],
  ['tel', 'তেল', 'tel', 'noun', 'tel', 'রান্নায় ব্যবহৃত পিচ্ছিল তরল।', 'oil', ['তৈল'], ['তরকারিতে তেল দাও।', 'Add oil to the curry.']],
  ['ghee', 'ঘি', 'ghi', 'noun', 'gʱi', 'দুধ থেকে তৈরি সুগন্ধি চর্বি।', 'clarified butter; ghee', [], ['ভাতে ঘি মেখে খাই।', 'I eat rice mixed with ghee.']],
  ['moshla', 'মশলা', 'moshla', 'noun', 'mɔʃla', 'রান্নার স্বাদ বাড়ানো গুঁড়া বা দানা।', 'spice', [], ['তরকারিতে মশলা দাও।', 'Add spice to the curry.']],
  ['tarkari', 'তরকারি', 'tarkari', 'noun', 'tɔrkari', 'রান্না করা সবজি বা মাংসের পদ।', 'curry; cooked dish', ['ব্যঞ্জন'], ['আজ মাছের তরকারি হয়েছে।', 'Fish curry was made today.']],
  ['sobji', 'সবজি', 'sobji', 'noun', 'ʃobdʒi', 'রান্নার উপযোগী ভোজ্য উদ্ভিদ।', 'vegetable', ['তরিতরকারি'], ['তাজা সবজি স্বাস্থ্যকর।', 'Fresh vegetables are healthy.']],
  ['alu', 'আলু', 'alu', 'noun', 'alu', 'মাটির নিচে জন্মানো গোলাকার সবজি।', 'potato', [], ['আলু ভাজা মজার।', 'Fried potato is tasty.']],
  ['pyaj', 'পেঁয়াজ', 'pyaj', 'noun', 'pẽaz', 'ঝাঁঝালো স্তরযুক্ত রান্নার সবজি।', 'onion', [], ['পেঁয়াজ কাটলে চোখে জল আসে।', 'Cutting onions brings tears.']],
  ['roshun', 'রসুন', 'roshun', 'noun', 'roʃun', 'ঝাঁঝালো গন্ধযুক্ত রান্নার মশলা।', 'garlic', [], ['রসুন খাবারে স্বাদ আনে।', 'Garlic adds flavor to food.']],
  ['lonka', 'লঙ্কা', 'lonka', 'noun', 'lɔŋka', 'ঝাল স্বাদের ছোট ফল; মরিচ।', 'chili pepper', ['মরিচ'], ['লঙ্কা খুব ঝাল।', 'The chili is very hot.']],
  ['modhu', 'মধু', 'modhu', 'noun', 'modʱu', 'মৌমাছির তৈরি মিষ্টি তরল।', 'honey', ['মকরন্দ'], ['মধু স্বাস্থ্যের জন্য ভালো।', 'Honey is good for health.']],
  ['doi', 'দই', 'doi', 'noun', 'doi', 'দুধ জমিয়ে তৈরি টক-মিষ্টি খাবার।', 'yogurt; curd', ['দধি'], ['খাওয়ার পরে দই খাই।', 'I eat yogurt after a meal.']],
  ['mishti', 'মিষ্টি', 'mishti', 'noun', 'miʃʈi', 'চিনি দিয়ে তৈরি মিষ্টি খাবার।', 'sweet; sweets', ['মিঠাই'], ['উৎসবে মিষ্টি বিলি হয়।', 'Sweets are shared during festivals.']],
  ['sorbot', 'শরবত', 'sorbot', 'noun', 'ʃɔrbot', 'ফল বা চিনির মিষ্টি ঠান্ডা পানীয়।', 'sherbet; cool drink', [], ['গরমে শরবত খেতে ভালো।', 'A cool drink is nice in the heat.']],

  // Time words.
  ['ekhon', 'এখন', 'ekhon', 'adverb', 'ækʰon', 'বর্তমান মুহূর্তে।', 'now', ['বর্তমানে'], ['আমি এখন ব্যস্ত।', 'I am busy now.']],
  ['tokhon', 'তখন', 'tokhon', 'adverb', 'tɔkʰon', 'সেই সময়ে; অতীতের কোনো মুহূর্তে।', 'then; at that time', [], ['তখন সন্ধ্যা হয়ে গিয়েছিল।', 'It was evening then.']],
  ['aj', 'আজ', 'aj', 'adverb', 'adʒ', 'বর্তমান দিনে।', 'today', ['অদ্য'], ['আজ ছুটির দিন।', 'Today is a holiday.']],
  ['kal', 'কাল', 'kal', 'noun', 'kal', 'গতকাল বা আগামীকাল; সময়।', 'yesterday; tomorrow', [], ['কাল আবার দেখা হবে।', 'We will meet again tomorrow.']],
  ['gotokal', 'গতকাল', 'gotokal', 'adverb', 'gɔtokal', 'আজকের আগের দিন।', 'yesterday', [], ['গতকাল বৃষ্টি হয়েছিল।', 'It rained yesterday.']],
  ['agamikal', 'আগামীকাল', 'agamikal', 'adverb', 'agamikal', 'আজকের পরের দিন।', 'tomorrow', [], ['আগামীকাল পরীক্ষা।', 'The exam is tomorrow.']],
  ['shokal_bela', 'ভোর', 'bhor', 'noun', 'bʱor', 'দিনের একেবারে শুরুর সময়।', 'dawn; early morning', ['ঊষা', 'প্রত্যুষ'], ['ভোরে পাখি ডাকে।', 'Birds sing at dawn.']],
  ['dupur', 'দুপুর', 'dupur', 'noun', 'dupur', 'দিনের মধ্যভাগ।', 'noon; midday', ['মধ্যাহ্ন'], ['দুপুরে রোদ প্রখর।', 'The sun is intense at noon.']],
  ['sondhya', 'সন্ধ্যা', 'sondhya', 'noun', 'ʃondʱæ', 'সূর্যাস্তের সময়।', 'evening', ['সাঁঝ'], ['সন্ধ্যায় প্রদীপ জ্বালাই।', 'We light lamps in the evening.']],
  ['ghonta', 'ঘণ্টা', 'ghonta', 'noun', 'gʱonʈa', 'ষাট মিনিটের সময়কাল।', 'hour', [], ['এক ঘণ্টা অপেক্ষা করলাম।', 'I waited for an hour.']],
  ['minit', 'মিনিট', 'minit', 'noun', 'miniʈ', 'ষাট সেকেন্ডের সময়কাল।', 'minute', [], ['পাঁচ মিনিট সময় দাও।', 'Give me five minutes.']],
  ['soptaho', 'সপ্তাহ', 'soptaho', 'noun', 'ʃɔptaho', 'সাত দিনের সময়কাল।', 'week', [], ['সপ্তাহে একদিন ছুটি।', 'There is one holiday a week.']],
  ['mash', 'মাস', 'mash', 'noun', 'maʃ', 'বছরের বারো ভাগের এক ভাগ।', 'month', [], ['প্রতি মাসে বেতন পাই।', 'I get a salary every month.']],

  // Verbs.
  ['bosha', 'বসা', 'bosha', 'verb', 'bɔʃa', 'আসন গ্রহণ করা; উপবেশন করা।', 'to sit', ['উপবেশন করা'], ['চেয়ারে বসো।', 'Sit on the chair.']],
  ['dan_verb', 'দাঁড়ানো', 'daranno', 'verb', 'dãɽano', 'সোজা হয়ে পায়ে ভর দিয়ে থাকা।', 'to stand', [], ['লাইনে দাঁড়াও।', 'Stand in the line.']],
  ['othha', 'ওঠা', 'otha', 'verb', 'oʈʰa', 'নিচ থেকে উপরে যাওয়া; জেগে ওঠা।', 'to rise; to get up', ['উত্থান করা'], ['সকালে তাড়াতাড়ি ওঠো।', 'Get up early in the morning.']],
  ['nama', 'নামা', 'nama', 'verb', 'nama', 'উপর থেকে নিচে আসা।', 'to descend; to get down', [], ['সিঁড়ি দিয়ে নামো।', 'Come down the stairs.']],
  ['kena', 'কেনা', 'kena', 'verb', 'kena', 'অর্থের বিনিময়ে জিনিস নেওয়া।', 'to buy', ['ক্রয় করা'], ['বাজার থেকে সবজি কিনি।', 'I buy vegetables from the market.']],
  ['becha', 'বেচা', 'becha', 'verb', 'betʃa', 'অর্থের বিনিময়ে জিনিস দেওয়া।', 'to sell', ['বিক্রয় করা'], ['সে ফল বেচে।', 'He sells fruit.']],
  ['khonja', 'খোঁজা', 'khonja', 'verb', 'kʰõdʒa', 'হারানো বা কাঙ্ক্ষিত কিছু অনুসন্ধান করা।', 'to search; to look for', ['অনুসন্ধান করা'], ['চাবিটা খুঁজছি।', 'I am looking for the key.']],
  ['paoa', 'পাওয়া', 'paoa', 'verb', 'paoa', 'কিছু লাভ করা বা অর্জন করা।', 'to get; to find', ['লাভ করা'], ['আমি চিঠিটা পেয়েছি।', 'I have received the letter.']],
  ['bhaba', 'ভাবা', 'bhaba', 'verb', 'bʱaba', 'মনে চিন্তা করা।', 'to think', ['চিন্তা করা'], ['ভেবে সিদ্ধান্ত নাও।', 'Think before deciding.']],
  ['jana', 'জানা', 'jana', 'verb', 'dʒana', 'কোনো তথ্য বা বিষয় বোঝা।', 'to know', [], ['আমি উত্তরটি জানি।', 'I know the answer.']],
  ['bojha', 'বোঝা', 'bojha', 'verb', 'bodʒʱa', 'অর্থ বা ভাব উপলব্ধি করা।', 'to understand', ['উপলব্ধি করা'], ['কথাটা বুঝেছ?', 'Did you understand this?']],
  ['sekha', 'শেখা', 'shekha', 'verb', 'ʃekʰa', 'নতুন জ্ঞান বা দক্ষতা অর্জন করা।', 'to learn', [], ['সে সাঁতার শিখছে।', 'He is learning to swim.']],
  ['sekhano', 'শেখানো', 'shekhano', 'verb', 'ʃekʰano', 'অন্যকে জ্ঞান বা দক্ষতা দেওয়া।', 'to teach', [], ['তিনি অঙ্ক শেখান।', 'He teaches mathematics.']],
  ['khola_verb', 'খোলা', 'khola', 'verb', 'kʰola', 'বন্ধ কিছু উন্মুক্ত করা।', 'to open', [], ['জানালাটা খোলো।', 'Open the window.']],
  ['bondho_kora', 'বন্ধ করা', 'bondho kora', 'verb', 'bɔndʱo kɔra', 'খোলা কিছু আটকে দেওয়া।', 'to close', [], ['দরজা বন্ধ করো।', 'Close the door.']],
  ['dhora', 'ধরা', 'dhora', 'verb', 'dʱɔra', 'হাত দিয়ে কিছু আঁকড়ে রাখা।', 'to hold; to catch', ['আঁকড়ানো'], ['বলটা ধরো।', 'Catch the ball.']],
  ['chhora', 'ছাড়া', 'chhara', 'verb', 'tʃʰaɽa', 'ধরে রাখা কিছু মুক্ত করা।', 'to release; to leave', ['মুক্ত করা'], ['পাখিটা ছেড়ে দাও।', 'Release the bird.']],
  ['thaka', 'থাকা', 'thaka', 'verb', 'tʰaka', 'কোনো স্থানে অবস্থান করা; বাস করা।', 'to stay; to live', ['অবস্থান করা'], ['সে শহরে থাকে।', 'He lives in the city.']],
  ['bhalobasha_v', 'ভালোবাসা', 'bhalobasha', 'verb', 'bʱalobaʃa', 'গভীর স্নেহ বা প্রেম অনুভব করা।', 'to love', [], ['মা সন্তানকে ভালোবাসেন।', 'A mother loves her child.']],

  // Adjectives and descriptors.
  ['shundor', 'সুন্দর', 'shundor', 'adjective', 'ʃundor', 'দেখতে মনোরম ও আকর্ষণীয়।', 'beautiful', ['মনোরম', 'রূপবান'], ['ফুলটি খুব সুন্দর।', 'The flower is very beautiful.']],
  ['bishri', 'বিশ্রী', 'bishri', 'adjective', 'biʃri', 'দেখতে অপ্রীতিকর; কুৎসিত।', 'ugly', ['কুৎসিত'], ['জায়গাটা বিশ্রী নোংরা।', 'The place is ugly and dirty.']],
  ['porishkar', 'পরিষ্কার', 'porishkar', 'adjective', 'poriʃkar', 'ময়লাহীন ও স্বচ্ছ।', 'clean; clear', ['নির্মল', 'স্বচ্ছ'], ['ঘরটি পরিষ্কার আছে।', 'The room is clean.']],
  ['nongra', 'নোংরা', 'nongra', 'adjective', 'nɔŋra', 'ময়লাযুক্ত ও অপরিচ্ছন্ন।', 'dirty', ['ময়লা', 'অপরিষ্কার'], ['জামাটা নোংরা হয়ে গেছে।', 'The shirt has become dirty.']],
  ['bhari', 'ভারী', 'bhari', 'adjective', 'bʱari', 'ওজনে বেশি।', 'heavy', ['গুরুভার'], ['ব্যাগটা খুব ভারী।', 'The bag is very heavy.']],
  ['halka', 'হালকা', 'halka', 'adjective', 'halka', 'ওজনে কম।', 'light (weight)', ['লঘু'], ['পালক খুব হালকা।', 'A feather is very light.']],
  ['shokto', 'শক্ত', 'shokto', 'adjective', 'ʃɔkto', 'কঠিন ও দৃঢ়; সহজে ভাঙে না।', 'hard; strong', ['কঠিন', 'দৃঢ়'], ['লোহা খুব শক্ত।', 'Iron is very hard.']],
  ['norom', 'নরম', 'norom', 'adjective', 'nɔrom', 'কোমল ও সহজে চাপা যায়।', 'soft', ['কোমল', 'মোলায়েম'], ['বালিশটা নরম।', 'The pillow is soft.']],
  ['mishti_adj', 'মিষ্টি', 'mishti', 'adjective', 'miʃʈi', 'চিনির মতো স্বাদযুক্ত।', 'sweet', ['মধুর'], ['আমটা খুব মিষ্টি।', 'The mango is very sweet.']],
  ['tita', 'তিতা', 'tita', 'adjective', 'tita', 'নিমের মতো অপ্রীতিকর স্বাদযুক্ত।', 'bitter', ['তিক্ত'], ['ওষুধটা তিতা।', 'The medicine is bitter.']],
  ['tok_sour', 'টক', 'tok', 'adjective', 'ʈɔk', 'লেবুর মতো অম্ল স্বাদযুক্ত।', 'sour', ['অম্ল'], ['তেঁতুল খুব টক।', 'Tamarind is very sour.']],
  ['ghono', 'ঘন', 'ghono', 'adjective', 'gʱɔno', 'পুরু ও নিবিড়; পাতলা নয়।', 'thick; dense', ['নিবিড়'], ['বনটি খুব ঘন।', 'The forest is very dense.']],
  ['patla', 'পাতলা', 'patla', 'adjective', 'patla', 'সরু ও কম পুরু।', 'thin', ['সরু'], ['কাগজটা পাতলা।', 'The paper is thin.']],
  ['sotej', 'সতেজ', 'sotej', 'adjective', 'ʃotedʒ', 'তাজা ও প্রাণবন্ত।', 'fresh', ['তাজা'], ['সতেজ ফুল সুগন্ধি ছড়ায়।', 'Fresh flowers spread fragrance.']],
  ['shanto', 'শান্ত', 'shanto', 'adjective', 'ʃanto', 'অস্থিরতাহীন ও ধীর।', 'calm; quiet', ['ধীর', 'নিরিবিলি'], ['হ্রদের জল শান্ত।', 'The lake water is calm.']],

  // Abstract and common concepts.
  ['shuru', 'শুরু', 'shuru', 'noun', 'ʃuru', 'কোনো কিছুর আরম্ভ।', 'beginning; start', ['আরম্ভ', 'সূচনা'], ['খেলা শুরু হয়েছে।', 'The game has started.']],
  ['shesh', 'শেষ', 'shesh', 'noun', 'ʃeʃ', 'কোনো কিছুর সমাপ্তি।', 'end; finish', ['সমাপ্তি', 'অন্ত'], ['গল্পের শেষ সুন্দর।', 'The end of the story is beautiful.']],
  ['gati', 'গতি', 'gati', 'noun', 'goti', 'চলার হার বা বেগ।', 'speed; motion', ['বেগ'], ['গাড়ির গতি বেশি।', 'The car speed is high.']],
  ['ojon', 'ওজন', 'ojon', 'noun', 'odʒon', 'কোনো বস্তুর ভার।', 'weight', ['ভার'], ['ব্যাগের ওজন মাপো।', 'Measure the weight of the bag.']],
  ['maap', 'মাপ', 'maap', 'noun', 'map', 'পরিমাণ বা আকারের হিসাব।', 'measure; size', ['পরিমাপ'], ['জামার মাপ নাও।', 'Take the measurement of the shirt.']],
  ['dhoron', 'ধরন', 'dhoron', 'noun', 'dʱɔron', 'প্রকার বা রকম।', 'type; kind', ['প্রকার', 'রকম'], ['নানা ধরনের ফুল আছে।', 'There are various kinds of flowers.']],
  ['karon', 'কারণ', 'karon', 'noun', 'karon', 'যে জন্য কিছু ঘটে; হেতু।', 'reason; cause', ['হেতু'], ['দেরির কারণ কী?', 'What is the reason for the delay?']],
  ['fol_result', 'ফলাফল', 'folafol', 'noun', 'fɔlafol', 'কোনো কাজের পরিণাম।', 'result; outcome', ['পরিণাম'], ['পরীক্ষার ফলাফল ভালো।', 'The exam result is good.']],
  ['niyom', 'নিয়ম', 'niyom', 'noun', 'niom', 'মেনে চলার বিধি।', 'rule; regulation', ['বিধি', 'নিয়মনীতি'], ['নিয়ম মেনে চলো।', 'Follow the rules.']],
  ['odhikar', 'অধিকার', 'odhikar', 'noun', 'odʱikar', 'বৈধ দাবি বা ক্ষমতা।', 'right; entitlement', ['হক'], ['শিক্ষা সবার অধিকার।', 'Education is everyone right.']],
  ['dayitto', 'দায়িত্ব', 'dayitto', 'noun', 'dajitto', 'পালন করার কর্তব্য।', 'responsibility; duty', ['কর্তব্য'], ['এটি আমার দায়িত্ব।', 'This is my responsibility.']],
  ['shopoth', 'শপথ', 'shopoth', 'noun', 'ʃɔpotʰ', 'গম্ভীর অঙ্গীকার বা প্রতিজ্ঞা।', 'oath; vow', ['প্রতিজ্ঞা'], ['সে সত্য বলার শপথ নিল।', 'He took an oath to tell the truth.']],
  ['shukh', 'সুখ', 'shukh', 'noun', 'ʃukʰ', 'স্বাচ্ছন্দ্য ও তৃপ্তির অবস্থা।', 'happiness; comfort', ['স্বাচ্ছন্দ্য'], ['সুখ টাকায় কেনা যায় না।', 'Happiness cannot be bought with money.']],
  ['sahos', 'সাহস', 'sahos', 'noun', 'ʃahoʃ', 'ভয়কে জয় করার মনোবল।', 'courage; bravery', ['বীরত্ব', 'হিম্মত'], ['তার অনেক সাহস।', 'He has great courage.']],

  // Places and everyday nouns.
  ['office', 'অফিস', 'ofis', 'noun', 'ofiʃ', 'যেখানে কর্মচারীরা কাজ করে।', 'office', ['কার্যালয়'], ['বাবা অফিসে গেছেন।', 'Father has gone to the office.']],
  ['hashpatal', 'হাসপাতাল', 'hashpatal', 'noun', 'haʃpatal', 'যেখানে রোগীর চিকিৎসা হয়।', 'hospital', ['চিকিৎসালয়'], ['রোগীকে হাসপাতালে নেওয়া হলো।', 'The patient was taken to the hospital.']],
  ['mondir', 'মন্দির', 'mondir', 'noun', 'mondir', 'দেবতার পূজার স্থান।', 'temple', ['দেবালয়'], ['সকালে মন্দিরে ঘণ্টা বাজে।', 'The temple bell rings in the morning.']],
  ['moshjid', 'মসজিদ', 'moshjid', 'noun', 'mɔsdʒid', 'নামাজ পড়ার স্থান।', 'mosque', [], ['মসজিদে আজান হচ্ছে।', 'The call to prayer is sounding at the mosque.']],
  ['setu', 'সেতু', 'setu', 'noun', 'ʃetu', 'নদী বা খাল পার হওয়ার নির্মিত পথ।', 'bridge', ['পুল', 'সাঁকো'], ['নদীর উপর সেতু আছে।', 'There is a bridge over the river.']],
  ['bagan', 'বাগান', 'bagan', 'noun', 'bagan', 'ফুল ও গাছের যত্নে গড়া জায়গা।', 'garden', ['উদ্যান'], ['বাগানে গোলাপ ফুটেছে।', 'Roses have bloomed in the garden.']],
  ['deyal', 'দেয়াল', 'deyal', 'noun', 'deal', 'ঘর বা জায়গা ঘেরা খাড়া গাঁথনি।', 'wall', ['প্রাচীর', 'ভিত'], ['দেয়ালে ছবি টাঙানো।', 'A picture hangs on the wall.']],
  ['chhad', 'ছাদ', 'chhad', 'noun', 'tʃʰad', 'ঘরের উপরের আচ্ছাদন।', 'roof; rooftop', ['ছাউনি'], ['ছাদে দাঁড়িয়ে আকাশ দেখি।', 'I stand on the roof and watch the sky.']],
  ['siri', 'সিঁড়ি', 'siri', 'noun', 'ʃĩɽi', 'উপরে-নিচে ওঠানামার ধাপ।', 'stairs', ['সোপান'], ['সিঁড়ি দিয়ে উপরে ওঠো।', 'Go up the stairs.']],
  ['bela', 'বেলা', 'bela', 'noun', 'bæla', 'দিনের একটি ভাগ বা সময়।', 'time of day', ['কাল'], ['বেলা হয়ে গেছে, ওঠো।', 'It is late in the day, get up.']],
  ['jaiga', 'জায়গা', 'jaiga', 'noun', 'dʒaega', 'নির্দিষ্ট স্থান বা অবস্থান।', 'place; space', ['স্থান'], ['এই জায়গাটি শান্ত।', 'This place is quiet.']],
  ['jinis', 'জিনিস', 'jinis', 'noun', 'dʒiniʃ', 'কোনো বস্তু বা দ্রব্য।', 'thing; object', ['বস্তু', 'দ্রব্য'], ['ব্যাগে অনেক জিনিস আছে।', 'There are many things in the bag.']],
  ['dorkar', 'দরকার', 'dorkar', 'noun', 'dɔrkar', 'প্রয়োজন বা আবশ্যকতা।', 'need; necessity', ['প্রয়োজন', 'আবশ্যক'], ['আমার এই বইটি দরকার।', 'I need this book.']],
  ['shorbonim', 'সর্বনাম', 'shorbonam', 'noun', 'ʃɔrbonam', 'নামের পরিবর্তে ব্যবহৃত শব্দ।', 'pronoun', [], ['আমি একটি সর্বনাম।', 'Ami is a pronoun.']],

  // A few common function and quality words.
  ['hyan', 'হ্যাঁ', 'han', 'other', 'hæ̃', 'সম্মতি বা স্বীকৃতির শব্দ।', 'yes', [], ['হ্যাঁ, আমি রাজি।', 'Yes, I agree.']],
  ['na', 'না', 'na', 'other', 'na', 'অস্বীকার বা নিষেধের শব্দ।', 'no; not', [], ['না, এটা ঠিক নয়।', 'No, this is not right.']],
  ['hoyto', 'হয়তো', 'hoyto', 'adverb', 'hɔjto', 'সম্ভবত; নিশ্চিত নয় এমন।', 'perhaps; maybe', ['সম্ভবত'], ['হয়তো কাল বৃষ্টি হবে।', 'Perhaps it will rain tomorrow.']],
  ['shob', 'সব', 'shob', 'adjective', 'ʃɔb', 'সমগ্র; সকল কিছু।', 'all; every', ['সকল', 'সমস্ত'], ['সব কাজ শেষ হয়েছে।', 'All the work is done.']],
  ['kichu', 'কিছু', 'kichu', 'other', 'kitʃu', 'অল্প পরিমাণ; কোনো জিনিস।', 'some; something', [], ['আমাকে কিছু জল দাও।', 'Give me some water.']],
  ['onek', 'অনেক', 'onek', 'adjective', 'onek', 'বিপুল পরিমাণ; বহু।', 'many; much', ['বহু', 'প্রচুর'], ['আকাশে অনেক তারা।', 'There are many stars in the sky.']],
  ['ekhane', 'এখানে', 'ekhane', 'adverb', 'ækʰane', 'এই স্থানে।', 'here', [], ['তুমি এখানে বসো।', 'You sit here.']],
  ['okhane', 'ওখানে', 'okhane', 'adverb', 'okʰane', 'ওই স্থানে।', 'there', ['সেখানে'], ['বইটা ওখানে রাখো।', 'Put the book there.']],
  ['bhitore', 'ভিতরে', 'bhitore', 'adverb', 'bʱitore', 'কোনো কিছুর ভেতরের দিকে।', 'inside', ['অভ্যন্তরে'], ['ঘরের ভিতরে এসো।', 'Come inside the room.']],
  ['baire', 'বাইরে', 'baire', 'adverb', 'baire', 'কোনো কিছুর বাইরের দিকে।', 'outside', [], ['শিশুরা বাইরে খেলছে।', 'The children are playing outside.']],
  ['upore', 'উপরে', 'upore', 'adverb', 'upore', 'কোনো কিছুর উপরের দিকে।', 'above; up', ['ঊর্ধ্বে'], ['টেবিলের উপরে বই আছে।', 'There is a book on the table.']],
  ['niche', 'নিচে', 'niche', 'adverb', 'nitʃe', 'কোনো কিছুর নিচের দিকে।', 'below; down', ['তলায়'], ['গাছের নিচে বসি।', 'I sit under the tree.']]
];

const entries = rows.map(([id, headword, roman, pos, ipa, defBn, defEn, synonyms, example]) => {
  const entry = {
    id,
    headword,
    headwordRoman: roman,
    partOfSpeech: pos,
    pronunciationIPA: ipa,
    senses: [{ definitionBn: defBn, definitionEn: defEn }],
  };
  if (synonyms && synonyms.length > 0) {
    entry.synonyms = synonyms;
  }
  if (example) {
    entry.examples = [{ bn: example[0], en: example[1] }];
  }
  return entry;
});

const file = {
  version: 1,
  language: 'bn-en',
  entries,
};

writeFileSync(outPath, JSON.stringify(file, null, 2) + '\n', 'utf8');
console.log(`Wrote ${entries.length} entries to ${outPath}`);
