// One time generator for the WordSetu seed dictionary.
//
// Authors an original CC0 seed dataset of common Bangla words. Every field here
// is original content written for WordSetu and is not copied from any
// copyrighted dictionary. Run with: node scripts/gen-seed.mjs
//
// The output is written to resources/dictionary/entries.json. This script is a
// build time authoring aid; the generated JSON is the checked in source of
// truth for the dictionary data.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'resources', 'dictionary', 'entries.json');

// Each tuple: [id, headword(bn), roman, pos, ipa, defBn, defEn, synonyms[], example?]
// example is [bn, en] or null. Content is original and public domain (CC0).
const rows = [
  ['ami', 'আমি', 'ami', 'pronoun', 'ami', 'কথা বলা ব্যক্তি নিজেকে যে শব্দে বোঝায়।', 'I', [], ['আমি বাড়ি যাচ্ছি।', 'I am going home.']],
  ['tumi', 'তুমি', 'tumi', 'pronoun', 'tumi', 'যাকে সম্বোধন করা হয় তাকে ঘনিষ্ঠভাবে বোঝানোর শব্দ।', 'you', [], ['তুমি কেমন আছ?', 'How are you?']],
  ['apni', 'আপনি', 'apni', 'pronoun', 'apni', 'সম্মানসূচকভাবে দ্বিতীয় ব্যক্তিকে বোঝানোর শব্দ।', 'you (respectful)', [], ['আপনি বসুন।', 'Please sit down.']],
  ['se', 'সে', 'she', 'pronoun', 'ʃe', 'তৃতীয় কোনো ব্যক্তিকে বোঝানোর শব্দ।', 'he; she', [], ['সে এখন এখানে নেই।', 'He is not here now.']],
  ['boi', 'বই', 'boi', 'noun', 'boi', 'ছাপানো বা লেখা পৃষ্ঠার বাঁধাই করা সংকলন।', 'book', ['পুস্তক', 'গ্রন্থ'], ['আমি একটি বই পড়ছি।', 'I am reading a book.']],
  ['jol', 'জল', 'jol', 'noun', 'dʒɔl', 'বর্ণহীন স্বচ্ছ তরল যা পান করা হয়।', 'water', ['পানি', 'বারি'], ['গ্লাসে জল আছে।', 'There is water in the glass.']],
  ['pani', 'পানি', 'pani', 'noun', 'pani', 'পানের যোগ্য স্বচ্ছ তরল।', 'water', ['জল', 'বারি'], ['আমাকে একটু পানি দাও।', 'Give me some water.']],
  ['agun', 'আগুন', 'agun', 'noun', 'agun', 'জ্বলন্ত তাপ ও আলো উৎপন্নকারী দহন।', 'fire', ['অগ্নি', 'হুতাশন'], ['আগুন খুব গরম।', 'Fire is very hot.']],
  ['batas', 'বাতাস', 'batas', 'noun', 'batas', 'চলমান বায়ু।', 'wind; air', ['হাওয়া', 'বায়ু'], ['ঠান্ডা বাতাস বইছে।', 'A cold wind is blowing.']],
  ['akash', 'আকাশ', 'akash', 'noun', 'akaʃ', 'পৃথিবীর উপরে বিস্তৃত নীল শূন্যস্থান।', 'sky', ['গগন', 'নভ'], ['আকাশ আজ পরিষ্কার।', 'The sky is clear today.']],
  ['mati', 'মাটি', 'mati', 'noun', 'mati', 'পৃথিবীর উপরিভাগের নরম স্তর যেখানে গাছ জন্মায়।', 'soil; earth', ['ভূমি', 'জমি'], ['মাটিতে বীজ বোনা হয়।', 'Seeds are sown in the soil.']],
  ['surjo', 'সূর্য', 'surjo', 'noun', 'ʃurdʒo', 'যে নক্ষত্র থেকে পৃথিবী আলো ও তাপ পায়।', 'sun', ['রবি', 'ভানু'], ['সকালে সূর্য ওঠে।', 'The sun rises in the morning.']],
  ['chand', 'চাঁদ', 'chand', 'noun', 'tʃãd', 'রাতের আকাশে দৃশ্যমান পৃথিবীর উপগ্রহ।', 'moon', ['শশী', 'ইন্দু'], ['আজ রাতে চাঁদ উঠেছে।', 'The moon has risen tonight.']],
  ['tara', 'তারা', 'tara', 'noun', 'tara', 'রাতের আকাশে জ্বলজ্বল করা দূরবর্তী নক্ষত্র।', 'star', ['নক্ষত্র', 'উডু'], ['আকাশে অনেক তারা।', 'There are many stars in the sky.']],
  ['gachh', 'গাছ', 'gachh', 'noun', 'gatʃʰ', 'শিকড়, কাণ্ড ও পাতা যুক্ত উদ্ভিদ।', 'tree; plant', ['বৃক্ষ', 'তরু'], ['বাড়ির সামনে একটি গাছ আছে।', 'There is a tree in front of the house.']],
  ['phul', 'ফুল', 'phul', 'noun', 'pʰul', 'গাছের রঙিন সুগন্ধি প্রজনন অংশ।', 'flower', ['পুষ্প', 'কুসুম'], ['বাগানে ফুল ফুটেছে।', 'Flowers have bloomed in the garden.']],
  ['pakhi', 'পাখি', 'pakhi', 'noun', 'pakʰi', 'পালকযুক্ত উড়তে সক্ষম প্রাণী।', 'bird', ['বিহঙ্গ', 'খেচর'], ['পাখি গান গায়।', 'The bird sings.']],
  ['machh', 'মাছ', 'machh', 'noun', 'matʃʰ', 'জলে বাস করা কানকো ও পাখনাযুক্ত প্রাণী।', 'fish', ['মীন', 'মৎস্য'], ['নদীতে মাছ আছে।', 'There are fish in the river.']],
  ['ghar', 'ঘর', 'ghar', 'noun', 'gʰɔr', 'বসবাসের জন্য নির্মিত কক্ষ বা বাসস্থান।', 'room; house', ['কক্ষ', 'গৃহ'], ['ঘরটি বড় ও পরিষ্কার।', 'The room is big and clean.']],
  ['bari', 'বাড়ি', 'bari', 'noun', 'baɽi', 'পরিবারের বসবাসের স্থান।', 'home; house', ['গৃহ', 'নিবাস'], ['সে বাড়ি ফিরেছে।', 'He has returned home.']],
  ['school', 'স্কুল', 'skul', 'noun', 'skul', 'যেখানে ছাত্রছাত্রীরা শিক্ষা লাভ করে।', 'school', ['বিদ্যালয়', 'পাঠশালা'], ['শিশুরা স্কুলে যায়।', 'The children go to school.']],
  ['boi_ghor', 'গ্রন্থাগার', 'granthagar', 'noun', 'grɔntʰagar', 'যেখানে বই সংগ্রহ ও পাঠ করা হয়।', 'library', ['পাঠাগার'], ['গ্রন্থাগারে অনেক বই আছে।', 'There are many books in the library.']],
  ['shohor', 'শহর', 'shohor', 'noun', 'ʃɔhor', 'ঘনবসতিপূর্ণ বড় জনপদ।', 'city; town', ['নগর', 'পুর'], ['শহরে অনেক মানুষ থাকে।', 'Many people live in the city.']],
  ['gram', 'গ্রাম', 'gram', 'noun', 'gram', 'ছোট গ্রামীণ জনবসতি।', 'village', ['পল্লি', 'পাড়াগাঁ'], ['আমার গ্রাম খুব সুন্দর।', 'My village is very beautiful.']],
  ['rasta', 'রাস্তা', 'rasta', 'noun', 'rasta', 'চলাচলের জন্য নির্মিত পথ।', 'road; street', ['পথ', 'সড়ক'], ['রাস্তা দিয়ে গাড়ি চলে।', 'Cars run on the road.']],
  ['nodi', 'নদী', 'nodi', 'noun', 'nodi', 'প্রবাহিত মিষ্টি জলের বড় ধারা।', 'river', ['তটিনী', 'স্রোতস্বিনী'], ['নদীতে নৌকা চলছে।', 'Boats are sailing on the river.']],
  ['shagor', 'সাগর', 'shagor', 'noun', 'ʃagor', 'বিশাল লবণাক্ত জলরাশি।', 'sea; ocean', ['সমুদ্র', 'জলধি'], ['সাগরের ঢেউ বড়।', 'The waves of the sea are big.']],
  ['pahar', 'পাহাড়', 'pahar', 'noun', 'pahaɽ', 'ভূমি থেকে উঁচু বিশাল শিলাস্তূপ।', 'mountain; hill', ['পর্বত', 'গিরি'], ['পাহাড়ে বরফ জমে।', 'Snow gathers on the mountain.']],
  ['bon', 'বন', 'bon', 'noun', 'bɔn', 'ঘন গাছপালায় ঢাকা এলাকা।', 'forest', ['অরণ্য', 'জঙ্গল'], ['বনে বাঘ থাকে।', 'Tigers live in the forest.']],
  ['manush', 'মানুষ', 'manush', 'noun', 'manuʃ', 'বুদ্ধিসম্পন্ন সামাজিক প্রাণী।', 'human; person', ['লোক', 'জন'], ['মানুষ সমাজে বাস করে।', 'Humans live in society.']],
  ['chhele', 'ছেলে', 'chhele', 'noun', 'tʃʰele', 'পুরুষ সন্তান বা বালক।', 'boy; son', ['বালক', 'পুত্র'], ['ছেলেটি মাঠে খেলছে।', 'The boy is playing in the field.']],
  ['meye', 'মেয়ে', 'meye', 'noun', 'meje', 'নারী সন্তান বা বালিকা।', 'girl; daughter', ['বালিকা', 'কন্যা'], ['মেয়েটি গান শেখে।', 'The girl learns to sing.']],
  ['baba', 'বাবা', 'baba', 'noun', 'baba', 'পিতা, জন্মদাতা পুরুষ অভিভাবক।', 'father', ['পিতা', 'জনক'], ['বাবা অফিসে গেছেন।', 'Father has gone to the office.']],
  ['ma', 'মা', 'ma', 'noun', 'ma', 'জননী, জন্মদাত্রী নারী অভিভাবক।', 'mother', ['জননী', 'মাতা'], ['মা রান্না করছেন।', 'Mother is cooking.']],
  ['bhai', 'ভাই', 'bhai', 'noun', 'bʱai', 'একই পিতামাতার পুরুষ সন্তান।', 'brother', ['ভ্রাতা', 'সহোদর'], ['আমার একটি ছোট ভাই আছে।', 'I have a younger brother.']],
  ['bon_r', 'বোন', 'bon', 'noun', 'bon', 'একই পিতামাতার নারী সন্তান।', 'sister', ['ভগিনী', 'সহোদরা'], ['বোন আমাকে সাহায্য করে।', 'My sister helps me.']],
  ['bondhu', 'বন্ধু', 'bondhu', 'noun', 'bondʱu', 'যাকে বিশ্বাস ও ভালোবাসা যায় এমন সঙ্গী।', 'friend', ['মিত্র', 'সখা'], ['সে আমার ভালো বন্ধু।', 'He is my good friend.']],
  ['shikkhok', 'শিক্ষক', 'shikkhok', 'noun', 'ʃikkʰok', 'যিনি শিক্ষা দেন।', 'teacher', ['গুরু', 'অধ্যাপক'], ['শিক্ষক পড়ান।', 'The teacher teaches.']],
  ['chhatro', 'ছাত্র', 'chhatro', 'noun', 'tʃʰatro', 'যে শিক্ষা গ্রহণ করে।', 'student', ['শিক্ষার্থী', 'শিষ্য'], ['ছাত্র মন দিয়ে পড়ে।', 'The student studies attentively.']],
  ['daktar', 'ডাক্তার', 'daktar', 'noun', 'daktar', 'যিনি রোগ চিকিৎসা করেন।', 'doctor', ['চিকিৎসক', 'বৈদ্য'], ['ডাক্তার রোগী দেখছেন।', 'The doctor is examining the patient.']],
  ['krishok', 'কৃষক', 'krishok', 'noun', 'kriʃok', 'যিনি জমি চাষ করেন।', 'farmer', ['চাষি', 'কৃষিজীবী'], ['কৃষক মাঠে কাজ করে।', 'The farmer works in the field.']],
  ['kaj', 'কাজ', 'kaj', 'noun', 'kadʒ', 'যা সম্পন্ন করতে হয় এমন কর্ম।', 'work; task', ['কর্ম', 'শ্রম'], ['আমার অনেক কাজ আছে।', 'I have a lot of work.']],
  ['somoy', 'সময়', 'somoy', 'noun', 'ʃomoj', 'ঘটনার ধারাবাহিক পরিমাপ।', 'time', ['কাল', 'বেলা'], ['সময় নষ্ট কোরো না।', 'Do not waste time.']],
  ['din', 'দিন', 'din', 'noun', 'din', 'সূর্যোদয় থেকে সূর্যাস্ত পর্যন্ত সময়।', 'day', ['দিবস', 'বার'], ['আজকের দিনটি সুন্দর।', 'Today is a beautiful day.']],
  ['rat', 'রাত', 'rat', 'noun', 'rat', 'সূর্যাস্ত থেকে সূর্যোদয় পর্যন্ত অন্ধকার সময়।', 'night', ['রজনী', 'নিশি'], ['রাতে আকাশে তারা দেখা যায়।', 'Stars are visible in the sky at night.']],
  ['sokal', 'সকাল', 'sokal', 'noun', 'ʃokal', 'দিনের প্রথম ভাগ।', 'morning', ['প্রভাত', 'ভোর'], ['সকালে হাঁটা ভালো।', 'Walking in the morning is good.']],
  ['bikel', 'বিকেল', 'bikel', 'noun', 'bikel', 'দুপুরের পর সন্ধ্যার আগের সময়।', 'afternoon', ['অপরাহ্ন'], ['বিকেলে আমরা খেলি।', 'We play in the afternoon.']],
  ['bochhor', 'বছর', 'bochhor', 'noun', 'botʃʰor', 'বারো মাসের সময়কাল।', 'year', ['বর্ষ', 'সন'], ['নতুন বছর শুরু হয়েছে।', 'The new year has begun.']],
  ['khabar', 'খাবার', 'khabar', 'noun', 'kʰabar', 'যা খাওয়া হয়।', 'food', ['আহার', 'খাদ্য'], ['খাবার গরম আছে।', 'The food is hot.']],
  ['bhat', 'ভাত', 'bhat', 'noun', 'bʱat', 'সেদ্ধ চাল, প্রধান খাদ্য।', 'cooked rice', ['অন্ন'], ['দুপুরে ভাত খাই।', 'I eat rice at noon.']],
  ['dudh', 'দুধ', 'dudh', 'noun', 'dudʱ', 'গবাদি পশু থেকে পাওয়া সাদা পুষ্টিকর তরল।', 'milk', ['ক্ষীর'], ['শিশু দুধ পান করে।', 'The child drinks milk.']],
  ['dim', 'ডিম', 'dim', 'noun', 'dim', 'পাখি বা মুরগির খোলাযুক্ত প্রজননকোষ।', 'egg', ['অণ্ড'], ['সকালে ডিম খেলাম।', 'I ate an egg in the morning.']],
  ['fol', 'ফল', 'fol', 'noun', 'fɔl', 'গাছের ভোজ্য মিষ্টি অংশ।', 'fruit', ['ফলমূল'], ['আম একটি মিষ্টি ফল।', 'The mango is a sweet fruit.']],
  ['am', 'আম', 'am', 'noun', 'am', 'গ্রীষ্মকালীন রসালো মিষ্টি ফল।', 'mango', ['আম্র'], ['গ্রীষ্মে আম পাকে।', 'Mangoes ripen in summer.']],
  ['kola', 'কলা', 'kola', 'noun', 'kola', 'লম্বাটে হলুদ খোসাযুক্ত মিষ্টি ফল।', 'banana', ['রম্ভা'], ['বাঁদর কলা খায়।', 'The monkey eats a banana.']],
  ['chaal', 'চাল', 'chaal', 'noun', 'tʃal', 'ধান থেকে পাওয়া শস্যদানা।', 'rice (uncooked)', ['তণ্ডুল'], ['বাজারে চালের দাম বেড়েছে।', 'The price of rice has risen in the market.']],
  ['nun', 'নুন', 'nun', 'noun', 'nun', 'রান্নায় ব্যবহৃত লবণাক্ত সাদা দানা।', 'salt', ['লবণ'], ['তরকারিতে নুন কম হয়েছে।', 'The curry has too little salt.']],
  ['chini', 'চিনি', 'chini', 'noun', 'tʃini', 'মিষ্টি স্বাদের সাদা দানা।', 'sugar', ['শর্করা'], ['চায়ে চিনি দাও।', 'Put sugar in the tea.']],
  ['cha', 'চা', 'cha', 'noun', 'tʃa', 'পাতা ফুটিয়ে তৈরি গরম পানীয়।', 'tea', [], ['সকালে এক কাপ চা খাই।', 'I drink a cup of tea in the morning.']],
  ['ranna', 'রান্না', 'ranna', 'noun', 'ranna', 'খাবার প্রস্তুত করার কাজ।', 'cooking', ['পাক'], ['মা রান্না করছেন।', 'Mother is cooking.']],
  ['bhalobasa', 'ভালোবাসা', 'bhalobasa', 'noun', 'bʱalobaʃa', 'গভীর স্নেহ ও অনুরাগ।', 'love', ['প্রেম', 'অনুরাগ'], ['ভালোবাসা মানুষকে কাছে টানে।', 'Love brings people close.']],
  ['ananda', 'আনন্দ', 'ananda', 'noun', 'anɔndo', 'সুখ ও খুশির অনুভূতি।', 'joy; happiness', ['সুখ', 'হর্ষ'], ['উৎসবে সবার মনে আনন্দ।', 'Everyone feels joy during the festival.']],
  ['dukkho', 'দুঃখ', 'dukkho', 'noun', 'dukkʰo', 'কষ্ট ও বেদনার অনুভূতি।', 'sorrow; grief', ['কষ্ট', 'বেদনা'], ['তার মনে অনেক দুঃখ।', 'There is much sorrow in his heart.']],
  ['bhoy', 'ভয়', 'bhoy', 'noun', 'bʱɔj', 'আশঙ্কা বা ভীতির অনুভূতি।', 'fear', ['ভীতি', 'শঙ্কা'], ['অন্ধকারে তার ভয় করে।', 'He feels fear in the dark.']],
  ['asha', 'আশা', 'asha', 'noun', 'aʃa', 'ভালো কিছু ঘটার প্রত্যাশা।', 'hope', ['প্রত্যাশা', 'ভরসা'], ['আশা কখনো হারিও না।', 'Never lose hope.']],
  ['shanti', 'শান্তি', 'shanti', 'noun', 'ʃanti', 'অস্থিরতাহীন স্থির অবস্থা।', 'peace', ['প্রশান্তি'], ['সবাই শান্তি চায়।', 'Everyone wants peace.']],
  ['bhasha', 'ভাষা', 'bhasha', 'noun', 'bʱaʃa', 'ভাব প্রকাশের শব্দ ও ধ্বনির ব্যবস্থা।', 'language', ['বুলি'], ['বাংলা আমার মাতৃভাষা।', 'Bangla is my mother tongue.']],
  ['bangla', 'বাংলা', 'bangla', 'noun', 'baŋla', 'বাঙালিদের ভাষা ও সংস্কৃতি।', 'Bangla; Bengali', [], ['আমি বাংলা ভালোবাসি।', 'I love Bangla.']],
  ['gaan', 'গান', 'gaan', 'noun', 'gan', 'সুরে গাওয়া কথা ও ধ্বনি।', 'song', ['সঙ্গীত', 'গীত'], ['সে সুন্দর গান গায়।', 'She sings beautiful songs.']],
  ['kobita', 'কবিতা', 'kobita', 'noun', 'kobita', 'ছন্দ ও ভাবে রচিত সাহিত্যরূপ।', 'poem; poetry', ['পদ্য', 'কাব্য'], ['সে একটি কবিতা লিখেছে।', 'He has written a poem.']],
  ['golpo', 'গল্প', 'golpo', 'noun', 'golpo', 'কল্পিত বা বাস্তব ঘটনার বিবরণ।', 'story', ['কাহিনি', 'আখ্যান'], ['দাদি রাতে গল্প বলেন।', 'Grandmother tells stories at night.']],
  ['chhobi', 'ছবি', 'chhobi', 'noun', 'tʃʰobi', 'রঙ ও রেখায় আঁকা দৃশ্য।', 'picture; image', ['চিত্র', 'প্রতিকৃতি'], ['দেয়ালে একটি ছবি টাঙানো।', 'A picture hangs on the wall.']],
  ['rong', 'রং', 'rong', 'noun', 'rɔŋ', 'বস্তুর দৃশ্যমান বর্ণ।', 'color', ['বর্ণ'], ['তার প্রিয় রং নীল।', 'His favorite color is blue.']],
  ['lal', 'লাল', 'lal', 'adjective', 'lal', 'রক্তের মতো বর্ণবিশিষ্ট।', 'red', ['রক্তবর্ণ'], ['তার একটি লাল জামা আছে।', 'She has a red dress.']],
  ['nil', 'নীল', 'nil', 'adjective', 'nil', 'আকাশ বা সমুদ্রের মতো বর্ণবিশিষ্ট।', 'blue', [], ['আকাশ নীল দেখায়।', 'The sky looks blue.']],
  ['shobuj', 'সবুজ', 'shobuj', 'adjective', 'ʃobudʒ', 'ঘাস বা পাতার মতো বর্ণবিশিষ্ট।', 'green', ['হরিৎ'], ['মাঠ সবুজ ঘাসে ঢাকা।', 'The field is covered in green grass.']],
  ['sada', 'সাদা', 'sada', 'adjective', 'ʃada', 'দুধ বা বরফের মতো বর্ণবিশিষ্ট।', 'white', ['শুভ্র', 'ধবল'], ['তার সাদা পোশাক পরিষ্কার।', 'His white clothes are clean.']],
  ['kalo', 'কালো', 'kalo', 'adjective', 'kalo', 'অন্ধকার বা কয়লার মতো বর্ণবিশিষ্ট।', 'black', ['কৃষ্ণ'], ['রাত কালো অন্ধকার।', 'The night is pitch black.']],
  ['boro', 'বড়', 'boro', 'adjective', 'bɔɽo', 'আকারে বা মাপে অধিক।', 'big; large', ['বৃহৎ', 'বিশাল'], ['এটি একটি বড় বাড়ি।', 'This is a big house.']],
  ['chhoto', 'ছোট', 'chhoto', 'adjective', 'tʃʰoto', 'আকারে বা মাপে কম।', 'small; little', ['ক্ষুদ্র'], ['তার একটি ছোট বিড়াল আছে।', 'She has a small cat.']],
  ['bhalo', 'ভালো', 'bhalo', 'adjective', 'bʱalo', 'গুণে বা মানে উত্তম।', 'good', ['উত্তম', 'সৎ'], ['সে খুব ভালো মানুষ।', 'He is a very good person.']],
  ['kharap', 'খারাপ', 'kharap', 'adjective', 'kʰarap', 'গুণে বা মানে মন্দ।', 'bad', ['মন্দ', 'অশুভ'], ['আজ আবহাওয়া খারাপ।', 'The weather is bad today.']],
  ['notun', 'নতুন', 'notun', 'adjective', 'notun', 'সম্প্রতি তৈরি বা আসা।', 'new', ['নব', 'নবীন'], ['সে একটি নতুন গাড়ি কিনেছে।', 'He has bought a new car.']],
  ['purono', 'পুরনো', 'purono', 'adjective', 'purono', 'দীর্ঘদিন ধরে থাকা বা ব্যবহৃত।', 'old', ['প্রাচীন', 'জীর্ণ'], ['এই বইটি অনেক পুরনো।', 'This book is very old.']],
  ['lomba', 'লম্বা', 'lomba', 'adjective', 'lɔmba', 'দৈর্ঘ্যে অধিক।', 'long; tall', ['দীর্ঘ'], ['সে দেখতে লম্বা।', 'He is tall.']],
  ['choto_khato', 'বেঁটে', 'bete', 'adjective', 'bɛʈe', 'উচ্চতায় কম।', 'short (in height)', ['খর্ব'], ['লোকটি একটু বেঁটে।', 'The man is a bit short.']],
  ['gorom', 'গরম', 'gorom', 'adjective', 'gɔrom', 'উচ্চ তাপমাত্রাযুক্ত।', 'hot; warm', ['উষ্ণ', 'তপ্ত'], ['গ্রীষ্মে আবহাওয়া গরম।', 'The weather is hot in summer.']],
  ['thanda', 'ঠান্ডা', 'thanda', 'adjective', 'ʈʰanda', 'নিম্ন তাপমাত্রাযুক্ত।', 'cold; cool', ['শীতল', 'হিম'], ['ঠান্ডা পানি খেতে ভালো।', 'Cold water is nice to drink.']],
  ['druto', 'দ্রুত', 'druto', 'adjective', 'druto', 'অধিক গতিসম্পন্ন।', 'fast; quick', ['ক্ষিপ্র', 'দ্রুতগামী'], ['ট্রেন দ্রুত চলে।', 'The train moves fast.']],
  ['dhire', 'ধীরে', 'dhire', 'adverb', 'dʱire', 'কম গতিতে; আস্তে।', 'slowly', ['আস্তে', 'মন্থর'], ['ধীরে ধীরে হাঁটো।', 'Walk slowly.']],
  ['unchu', 'উঁচু', 'unchu', 'adjective', 'ũtʃu', 'উপরের দিকে অধিক বিস্তৃত।', 'high; tall', ['উচ্চ'], ['পাহাড় খুব উঁচু।', 'The mountain is very high.']],
  ['nichu', 'নিচু', 'nichu', 'adjective', 'nitʃu', 'নিচের দিকে অবস্থিত; কম উঁচু।', 'low', ['নিম্ন'], ['জায়গাটি একটু নিচু।', 'The place is a bit low.']],
  ['khola', 'খোলা', 'khola', 'adjective', 'kʰola', 'বন্ধ নয় এমন; উন্মুক্ত।', 'open', ['উন্মুক্ত'], ['দরজা খোলা আছে।', 'The door is open.']],
  ['bondho', 'বন্ধ', 'bondho', 'adjective', 'bɔndʱo', 'খোলা নয় এমন; রুদ্ধ।', 'closed; shut', ['রুদ্ধ'], ['দোকান আজ বন্ধ।', 'The shop is closed today.']],
  ['jawa', 'যাওয়া', 'jawa', 'verb', 'dʒaoa', 'এক স্থান থেকে অন্য স্থানে সরে যাওয়া।', 'to go', ['গমন করা'], ['আমাকে এখন যেতে হবে।', 'I have to go now.']],
  ['asha_v', 'আসা', 'asha', 'verb', 'aʃa', 'কোনো স্থানে পৌঁছানো বা আগমন করা।', 'to come', ['আগমন করা'], ['সে কাল আসবে।', 'He will come tomorrow.']],
  ['khawa', 'খাওয়া', 'khawa', 'verb', 'kʰaoa', 'খাদ্য গ্রহণ করা।', 'to eat', ['ভক্ষণ করা'], ['আমরা একসঙ্গে খাব।', 'We will eat together.']],
  ['pora', 'পড়া', 'pora', 'verb', 'pɔɽa', 'লেখা বুঝে পাঠ করা; অধ্যয়ন করা।', 'to read; to study', ['অধ্যয়ন করা'], ['সে বই পড়ছে।', 'She is reading a book.']],
  ['lekha', 'লেখা', 'lekha', 'verb', 'lekʰa', 'কলম বা যন্ত্রে শব্দ অঙ্কন করা।', 'to write', ['রচনা করা'], ['সে চিঠি লিখছে।', 'He is writing a letter.']],
  ['bola', 'বলা', 'bola', 'verb', 'bɔla', 'কথা প্রকাশ করা; উচ্চারণ করা।', 'to say; to speak', ['কহা'], ['সত্য কথা বলো।', 'Speak the truth.']],
  ['shona', 'শোনা', 'shona', 'verb', 'ʃona', 'কান দিয়ে ধ্বনি গ্রহণ করা।', 'to hear; to listen', ['শ্রবণ করা'], ['গান শুনতে ভালো লাগে।', 'I like listening to songs.']],
  ['dekha', 'দেখা', 'dekha', 'verb', 'dɛkʰa', 'চোখ দিয়ে অনুভব করা।', 'to see; to look', ['দর্শন করা'], ['আকাশ দেখো কত সুন্দর।', 'Look how beautiful the sky is.']],
  ['kora', 'করা', 'kora', 'verb', 'kɔra', 'কোনো কাজ সম্পন্ন করা।', 'to do; to make', ['সম্পাদন করা'], ['কাজটি ঠিকমতো করো।', 'Do the task properly.']],
  ['deoa', 'দেওয়া', 'deoa', 'verb', 'dɛoa', 'কিছু হাতে তুলে দেওয়া বা প্রদান করা।', 'to give', ['প্রদান করা'], ['আমাকে বইটি দাও।', 'Give me the book.']],
  ['neoa', 'নেওয়া', 'neoa', 'verb', 'nɛoa', 'কিছু গ্রহণ করা বা নিজের কাছে রাখা।', 'to take', ['গ্রহণ করা'], ['ছাতাটি সঙ্গে নাও।', 'Take the umbrella with you.']],
  ['ghumano', 'ঘুমানো', 'ghumano', 'verb', 'gʱumano', 'নিদ্রা যাওয়া; বিশ্রাম নেওয়া।', 'to sleep', ['নিদ্রা যাওয়া'], ['শিশু ঘুমাচ্ছে।', 'The baby is sleeping.']],
  ['hasha', 'হাসা', 'hasha', 'verb', 'haʃa', 'আনন্দে মুখে হাসি প্রকাশ করা।', 'to laugh; to smile', [], ['সে মন খুলে হাসে।', 'She laughs heartily.']],
  ['kanna', 'কান্না', 'kanna', 'noun', 'kanna', 'দুঃখে বা কষ্টে চোখের জল ফেলা।', 'crying; weeping', ['ক্রন্দন'], ['শিশুর কান্না থামছে না।', 'The baby will not stop crying.']],
  ['hata', 'হাঁটা', 'hata', 'verb', 'hãʈa', 'পায়ে হেঁটে চলা।', 'to walk', ['পদব্রজে চলা'], ['সকালে হাঁটা স্বাস্থ্যকর।', 'Walking in the morning is healthy.']],
  ['dourano', 'দৌড়ানো', 'dourano', 'verb', 'douɽano', 'দ্রুত গতিতে পায়ে চলা।', 'to run', ['ধাবন করা'], ['সে মাঠে দৌড়াচ্ছে।', 'He is running in the field.']],
  ['khela', 'খেলা', 'khela', 'noun', 'kʰɛla', 'বিনোদন বা প্রতিযোগিতার কাজ।', 'game; play', ['ক্রীড়া'], ['শিশুরা খেলা করছে।', 'The children are playing.']],
  ['kaj_kora', 'পরিশ্রম', 'porishrom', 'noun', 'poriʃrom', 'কঠোর মেহনত বা খাটুনি।', 'hard work; labor', ['মেহনত', 'শ্রম'], ['পরিশ্রমে সফলতা আসে।', 'Success comes through hard work.']],
  ['taka', 'টাকা', 'taka', 'noun', 'ʈaka', 'বাংলাদেশের মুদ্রা; অর্থ।', 'money; taka', ['অর্থ', 'মুদ্রা'], ['তার কাছে অনেক টাকা।', 'He has a lot of money.']],
  ['bajar', 'বাজার', 'bajar', 'noun', 'badʒar', 'যেখানে জিনিস কেনাবেচা হয়।', 'market', ['হাট'], ['মা বাজারে গেছেন।', 'Mother has gone to the market.']],
  ['dokan', 'দোকান', 'dokan', 'noun', 'dokan', 'যেখানে পণ্য বিক্রি হয়।', 'shop; store', ['বিপণি'], ['দোকানে নতুন জিনিস এসেছে।', 'New items have arrived at the shop.']],
  ['gari', 'গাড়ি', 'gari', 'noun', 'gaɽi', 'চাকাযুক্ত যানবাহন।', 'car; vehicle', ['যান', 'বাহন'], ['গাড়ি রাস্তায় চলছে।', 'The car is moving on the road.']],
  ['train', 'ট্রেন', 'tren', 'noun', 'ʈren', 'রেললাইনে চলা দীর্ঘ যান।', 'train', ['রেলগাড়ি'], ['ট্রেন সময়মতো এসেছে।', 'The train arrived on time.']],
  ['nouka', 'নৌকা', 'nouka', 'noun', 'nouka', 'জলে চলার ছোট যান।', 'boat', ['তরি', 'ডিঙি'], ['নৌকা নদীতে ভাসছে।', 'The boat floats on the river.']],
  ['hat', 'হাত', 'hat', 'noun', 'hat', 'শরীরের যে অঙ্গ দিয়ে ধরা হয়।', 'hand', ['কর', 'পাণি'], ['হাত ধুয়ে খাও।', 'Wash your hands before eating.']],
  ['pa', 'পা', 'pa', 'noun', 'pa', 'শরীরের যে অঙ্গ দিয়ে হাঁটা হয়।', 'foot; leg', ['চরণ', 'পদ'], ['তার পায়ে ব্যথা।', 'His foot hurts.']],
  ['chokh', 'চোখ', 'chokh', 'noun', 'tʃokʰ', 'শরীরের যে অঙ্গ দিয়ে দেখা হয়।', 'eye', ['নয়ন', 'আঁখি'], ['তার চোখ দুটি সুন্দর।', 'Her eyes are beautiful.']],
  ['kan', 'কান', 'kan', 'noun', 'kan', 'শরীরের যে অঙ্গ দিয়ে শোনা হয়।', 'ear', ['কর্ণ', 'শ্রবণ'], ['কান দিয়ে শব্দ শুনি।', 'We hear sound with our ears.']],
  ['mukh', 'মুখ', 'mukh', 'noun', 'mukʰ', 'মুখমণ্ডল; কথা বলার অঙ্গ।', 'face; mouth', ['বদন', 'আনন'], ['তার মুখে হাসি।', 'There is a smile on his face.']],
  ['matha', 'মাথা', 'matha', 'noun', 'matʰa', 'শরীরের উপরের অংশ; মস্তক।', 'head', ['মস্তক', 'শির'], ['তার মাথা ব্যথা করছে।', 'His head is aching.']],
  ['mon', 'মন', 'mon', 'noun', 'mɔn', 'চিন্তা ও অনুভূতির কেন্দ্র।', 'mind; heart', ['চিত্ত', 'হৃদয়'], ['তার মন আজ খুশি।', 'His mind is happy today.']],
  ['gyan', 'জ্ঞান', 'gyan', 'noun', 'ggæn', 'জানা ও বোঝার ক্ষমতা।', 'knowledge', ['বিদ্যা', 'প্রজ্ঞা'], ['জ্ঞান মানুষকে আলোকিত করে।', 'Knowledge enlightens people.']],
  ['shotto', 'সত্য', 'shotto', 'noun', 'ʃotto', 'যা সঠিক ও বাস্তব।', 'truth', ['যথার্থ'], ['সত্য কখনো লুকায় না।', 'Truth never stays hidden.']],
  ['mittha', 'মিথ্যা', 'mittha', 'noun', 'mittʰa', 'যা সত্য নয়; অসত্য।', 'lie; falsehood', ['অসত্য'], ['মিথ্যা বলা উচিত নয়।', 'One should not tell lies.']],
  ['shopno', 'স্বপ্ন', 'shopno', 'noun', 'ʃɔpno', 'ঘুমের মধ্যে দেখা দৃশ্য; আকাঙ্ক্ষা।', 'dream', [], ['তার একটি বড় স্বপ্ন আছে।', 'He has a big dream.']],
  ['prithibi', 'পৃথিবী', 'prithibi', 'noun', 'pritʰibi', 'আমরা যে গ্রহে বাস করি।', 'earth; world', ['ধরা', 'বসুন্ধরা'], ['পৃথিবী সূর্যের চারদিকে ঘোরে।', 'The earth revolves around the sun.']],
  ['brishti', 'বৃষ্টি', 'brishti', 'noun', 'briʃʈi', 'মেঘ থেকে পড়া জল।', 'rain', ['বর্ষণ'], ['বৃষ্টিতে মাটি ভিজে গেছে।', 'The soil is wet from the rain.']],
  ['megh', 'মেঘ', 'megh', 'noun', 'megʱ', 'আকাশে জমা জলীয় বাষ্প।', 'cloud', ['জলধর'], ['আকাশে কালো মেঘ জমেছে।', 'Dark clouds have gathered in the sky.']],
  ['shishu', 'শিশু', 'shishu', 'noun', 'ʃiʃu', 'ছোট বয়সের বাচ্চা।', 'child; baby', ['বাচ্চা', 'শাবক'], ['শিশুটি হাসছে।', 'The baby is smiling.']],
  ['bura', 'বৃদ্ধ', 'briddho', 'adjective', 'briddʱo', 'বয়সে প্রবীণ।', 'old (person); elderly', ['প্রবীণ'], ['বৃদ্ধ লোকটি ধীরে হাঁটেন।', 'The old man walks slowly.']],
  ['jibon', 'জীবন', 'jibon', 'noun', 'dʒibon', 'বেঁচে থাকার অবস্থা।', 'life', ['প্রাণ', 'আয়ু'], ['জীবন খুব মূল্যবান।', 'Life is very precious.']],
  ['mrittu', 'মৃত্যু', 'mrittu', 'noun', 'mrittu', 'জীবনের অবসান।', 'death', ['মরণ'], ['মৃত্যু জীবনের অনিবার্য সত্য।', 'Death is the inevitable truth of life.']],
  ['shorir', 'শরীর', 'shorir', 'noun', 'ʃorir', 'প্রাণীর দেহ।', 'body', ['দেহ', 'কায়া'], ['ব্যায়ামে শরীর সুস্থ থাকে।', 'Exercise keeps the body healthy.']],
  ['rog', 'রোগ', 'rog', 'noun', 'rog', 'শরীরের অসুস্থ অবস্থা।', 'disease; illness', ['ব্যাধি', 'অসুখ'], ['সময়মতো রোগের চিকিৎসা দরকার।', 'A disease needs timely treatment.']],
  ['oushudh', 'ওষুধ', 'oushudh', 'noun', 'ouʃudʱ', 'রোগ সারাতে ব্যবহৃত দ্রব্য।', 'medicine', ['ঔষধ', 'দাওয়াই'], ['ডাক্তার ওষুধ দিয়েছেন।', 'The doctor has given medicine.']],
  ['alo', 'আলো', 'alo', 'noun', 'alo', 'যা দিয়ে দেখা যায়; দীপ্তি।', 'light', ['জ্যোতি', 'দীপ্তি'], ['ঘরে আলো জ্বলছে।', 'The light is on in the room.']],
  ['andhokar', 'অন্ধকার', 'andhokar', 'noun', 'ɔndʱokar', 'আলোর অভাব।', 'darkness', ['তমসা', 'আঁধার'], ['রাতে চারদিকে অন্ধকার।', 'It is dark all around at night.']],
  ['shokti', 'শক্তি', 'shokti', 'noun', 'ʃokti', 'কাজ করার সামর্থ্য বা বল।', 'power; strength; energy', ['বল', 'ক্ষমতা'], ['সূর্য থেকে শক্তি পাওয়া যায়।', 'Energy is obtained from the sun.']],
  ['shomoy_shuchi', 'ইতিহাস', 'itihas', 'noun', 'itihaʃ', 'অতীত ঘটনার লিখিত বিবরণ।', 'history', ['পুরাবৃত্ত'], ['আমরা দেশের ইতিহাস পড়ি।', 'We study the history of the country.']],
  ['bigyan', 'বিজ্ঞান', 'bigyan', 'noun', 'biggæn', 'পর্যবেক্ষণ ও পরীক্ষার মাধ্যমে অর্জিত জ্ঞান।', 'science', [], ['বিজ্ঞান আমাদের জীবন সহজ করেছে।', 'Science has made our lives easier.']],
  ['ganit', 'গণিত', 'ganit', 'noun', 'gonit', 'সংখ্যা ও পরিমাণ নিয়ে বিদ্যা।', 'mathematics', ['অঙ্কশাস্ত্র'], ['গণিত আমার প্রিয় বিষয়।', 'Mathematics is my favorite subject.']],
  ['kolom', 'কলম', 'kolom', 'noun', 'kɔlom', 'লেখার জন্য কালিভরা যন্ত্র।', 'pen', ['লেখনী'], ['কলম দিয়ে লিখি।', 'I write with a pen.']],
  ['kagoj', 'কাগজ', 'kagoj', 'noun', 'kagodʒ', 'লেখা ও ছাপার পাতলা উপাদান।', 'paper', ['পত্র'], ['কাগজে ছবি আঁকি।', 'I draw a picture on paper.']],
  ['darja', 'দরজা', 'darja', 'noun', 'dɔrdʒa', 'ঘরে ঢোকার মুখ।', 'door', ['কপাট', 'দ্বার'], ['দরজাটি বন্ধ করো।', 'Close the door.']],
  ['janala', 'জানালা', 'janala', 'noun', 'dʒanala', 'ঘরের যে ফাঁক দিয়ে আলো-বাতাস আসে।', 'window', ['বাতায়ন', 'গবাক্ষ'], ['জানালা দিয়ে বাতাস আসে।', 'Air comes in through the window.']],
  ['bichana', 'বিছানা', 'bichana', 'noun', 'bitʃana', 'ঘুমানোর জন্য পাতা শয্যা।', 'bed', ['শয্যা'], ['সে বিছানায় শুয়ে আছে।', 'She is lying on the bed.']],
  ['jama', 'জামা', 'jama', 'noun', 'dʒama', 'শরীরে পরিধেয় পোশাক।', 'shirt; clothes', ['বস্ত্র', 'পোশাক'], ['তার নতুন জামা পছন্দ হয়েছে।', 'He liked his new shirt.']],
  ['juta', 'জুতা', 'juta', 'noun', 'dʒuta', 'পায়ে পরার আবরণ।', 'shoe', ['পাদুকা'], ['জুতা পরে বাইরে যাও।', 'Wear shoes when going out.']],
  ['ghori', 'ঘড়ি', 'ghori', 'noun', 'gʱoɽi', 'সময় দেখার যন্ত্র।', 'clock; watch', ['সময়যন্ত্র'], ['ঘড়িতে এখন দশটা।', 'It is ten o clock now.']],
  ['chabi', 'চাবি', 'chabi', 'noun', 'tʃabi', 'তালা খোলা ও বন্ধ করার যন্ত্র।', 'key', ['কুঞ্চিকা'], ['দরজার চাবি হারিয়ে গেছে।', 'The door key is lost.']],
  ['ayna', 'আয়না', 'ayna', 'noun', 'ajna', 'যে কাঁচে নিজের প্রতিবিম্ব দেখা যায়।', 'mirror', ['দর্পণ'], ['আয়নায় নিজেকে দেখি।', 'I look at myself in the mirror.']],
  ['bidyut', 'বিদ্যুৎ', 'bidyut', 'noun', 'biddut', 'তড়িৎ শক্তি।', 'electricity', ['তড়িৎ', 'বিজলি'], ['বিদ্যুৎ চলে গেছে।', 'The electricity has gone out.']],
  ['agni', 'তাপ', 'tap', 'noun', 'tap', 'গরম হওয়ার অনুভূতি বা শক্তি।', 'heat', ['উত্তাপ'], ['সূর্যের তাপ প্রখর।', 'The heat of the sun is intense.']],
  ['borsha', 'বর্ষা', 'borsha', 'noun', 'bɔrʃa', 'বৃষ্টিবহুল ঋতু।', 'monsoon; rainy season', [], ['বর্ষায় নদী ভরে ওঠে।', 'Rivers fill up during the monsoon.']],
  ['shirt_kal', 'শীত', 'shit', 'noun', 'ʃit', 'ঠান্ডা ঋতু।', 'winter', ['শীতকাল'], ['শীতে সবাই গরম কাপড় পরে।', 'Everyone wears warm clothes in winter.']],
  ['grishmo', 'গ্রীষ্ম', 'grishmo', 'noun', 'griʃʃo', 'গরম ঋতু।', 'summer', ['গ্রীষ্মকাল'], ['গ্রীষ্মে দিন বড় হয়।', 'Days are longer in summer.']],
  ['bosonto', 'বসন্ত', 'bosonto', 'noun', 'bɔʃonto', 'ফুল ফোটার ঋতু।', 'spring', [], ['বসন্তে গাছে নতুন পাতা আসে।', 'New leaves appear on trees in spring.']],
  ['desh', 'দেশ', 'desh', 'noun', 'deʃ', 'নির্দিষ্ট সীমানার ভূখণ্ড ও জাতি।', 'country', ['রাষ্ট্র', 'ভূখণ্ড'], ['আমি আমার দেশকে ভালোবাসি।', 'I love my country.']],
  ['manchitro', 'মানচিত্র', 'manchitro', 'noun', 'mantʃitro', 'ভূখণ্ডের অঙ্কিত চিত্র।', 'map', [], ['মানচিত্রে নদী দেখানো আছে।', 'The river is shown on the map.']],
  ['itihaser_boi', 'সংবাদ', 'shongbad', 'noun', 'ʃoŋbad', 'নতুন ঘটনার খবর।', 'news', ['খবর', 'বার্তা'], ['সকালে সংবাদ পড়ি।', 'I read the news in the morning.']],
  ['prosno', 'প্রশ্ন', 'proshno', 'noun', 'proʃno', 'উত্তর জানতে চাওয়া কথা।', 'question', ['জিজ্ঞাসা'], ['তার প্রশ্নের উত্তর দাও।', 'Answer his question.']],
  ['uttor', 'উত্তর', 'uttor', 'noun', 'uttor', 'প্রশ্নের জবাব; একটি দিক।', 'answer; north', ['জবাব'], ['তার উত্তর সঠিক ছিল।', 'His answer was correct.']],
  ['shomadhan', 'সমাধান', 'shomadhan', 'noun', 'ʃomadʱan', 'সমস্যার নিষ্পত্তি।', 'solution', ['নিষ্পত্তি'], ['সমস্যার সমাধান পাওয়া গেছে।', 'A solution to the problem has been found.']],
  ['shomossa', 'সমস্যা', 'shomossa', 'noun', 'ʃomoʃʃa', 'যা সমাধান করা প্রয়োজন।', 'problem', ['ঝামেলা'], ['এটি একটি কঠিন সমস্যা।', 'This is a difficult problem.']],
  ['shongkhya', 'সংখ্যা', 'shongkhya', 'noun', 'ʃoŋkʰæ', 'গণনার একক; নম্বর।', 'number', ['নম্বর', 'অঙ্ক'], ['পাঁচ একটি ছোট সংখ্যা।', 'Five is a small number.']],
  ['nam', 'নাম', 'nam', 'noun', 'nam', 'পরিচয়ের জন্য দেওয়া শব্দ।', 'name', ['অভিধা'], ['তার নাম কী?', 'What is his name?']],
  ['kotha', 'কথা', 'kotha', 'noun', 'kɔtʰa', 'উচ্চারিত বা লিখিত বাক্য।', 'word; talk', ['বাণী', 'বাক্য'], ['তার কথা সবাই শোনে।', 'Everyone listens to what he says.']],
  ['chithi', 'চিঠি', 'chithi', 'noun', 'tʃiʈʰi', 'লিখিত বার্তা যা পাঠানো হয়।', 'letter', ['পত্র'], ['সে বন্ধুকে চিঠি লিখেছে।', 'He has written a letter to his friend.']],
  ['upohar', 'উপহার', 'upohar', 'noun', 'upohar', 'ভালোবাসা বা সম্মানে দেওয়া জিনিস।', 'gift; present', ['উপঢৌকন'], ['সে আমাকে উপহার দিয়েছে।', 'She has given me a gift.']],
  ['utsob', 'উৎসব', 'utsob', 'noun', 'utʃʃɔb', 'আনন্দের সামাজিক অনুষ্ঠান।', 'festival', ['পার্বণ'], ['গ্রামে উৎসব চলছে।', 'A festival is going on in the village.']],
  ['bijoy', 'বিজয়', 'bijoy', 'noun', 'bidʒoj', 'জয় বা সাফল্য।', 'victory', ['জয়', 'বিজয়লাভ'], ['দলটি বিজয় অর্জন করেছে।', 'The team has achieved victory.']],
  ['shadhinota', 'স্বাধীনতা', 'shadhinota', 'noun', 'ʃadʱinota', 'পরাধীনতা থেকে মুক্ত অবস্থা।', 'freedom; independence', ['মুক্তি'], ['স্বাধীনতা সবার অধিকার।', 'Freedom is everyone right.']],
  ['nyay', 'ন্যায়', 'nyay', 'noun', 'næj', 'সঠিক ও সুবিচারপূর্ণ আচরণ।', 'justice', ['সুবিচার'], ['বিচারক ন্যায় প্রতিষ্ঠা করেন।', 'The judge establishes justice.']],
  ['shahajjo', 'সাহায্য', 'shahajjo', 'noun', 'ʃahaddʒo', 'অন্যকে সহযোগিতা করা।', 'help; aid', ['সহযোগিতা', 'উপকার'], ['বিপদে বন্ধুর সাহায্য পেয়েছি।', 'I got my friend help in trouble.']],
  ['bishwas', 'বিশ্বাস', 'bishwas', 'noun', 'biʃʃaʃ', 'কারও বা কিছুর প্রতি আস্থা।', 'trust; belief', ['আস্থা', 'ভরসা'], ['তার প্রতি আমার বিশ্বাস আছে।', 'I have trust in him.']],
  ['shomman', 'সম্মান', 'shomman', 'noun', 'ʃomman', 'শ্রদ্ধা ও মর্যাদা।', 'respect; honor', ['শ্রদ্ধা', 'মর্যাদা'], ['বড়দের সম্মান করা উচিত।', 'One should respect elders.']]
];

const entries = rows.map(([id, headword, roman, pos, ipa, defBn, defEn, synonyms, example]) => {
  const entry = {
    id,
    headword,
    headwordRoman: roman,
    partOfSpeech: pos,
    pronunciationIPA: ipa,
    senses: [{ definitionBn: defBn, definitionEn: defEn }],
  };
  if (synonyms && synonyms.length > 0) {
    entry.synonyms = synonyms;
  }
  if (example) {
    entry.examples = [{ bn: example[0], en: example[1] }];
  }
  return entry;
});

const file = {
  version: 1,
  language: 'bn-en',
  entries,
};

writeFileSync(outPath, JSON.stringify(file, null, 2) + '\n', 'utf8');
console.log(`Wrote ${entries.length} entries to ${outPath}`);
